export const contactme_page = {
  br: {
  title: "Vamos conversar?",
  description:
    "Entre em contato comigo para discutir oportunidades de colaboração, projetos ou simplesmente para trocar ideias. Estou sempre aberto a novas conexões e oportunidades de aprendizado.",
  phone_label: "Telefone",
  phone: "+55 (92) 98415-8067",
  phone_href: "+5592984158067",
  phone_link: "+55 (92) 98415-8067",
  myEmail_label: "E-mail",
  myEmail: "emidioaranhadeveloper@gmail.com",
  myEmail_link: "emidioaranhadeveloper@gmail.com",
  linkedin_label: "LinkedIn",
  linkedin_url: "https://www.linkedin.com/in/emidio-aranha/",
  linkedin_link: "emidio-aranha",
  github_label: "GitHub",
  github: "https://github.com/EmidioAranha13",
  github_link: "EmidioAranha13",
  location_label: "Localização",
  location: "Manaus, AM — Brasil",
  name_label: "Nome",
  name_placeholder: "Seu nome",
  email_label: "E-mail",
  email_placeholder: "seu@email.com",
  yourContact: "Seu telefone",
  yourContact_placeholder: "Seu número de telefone",
  form_phone_invalid_message: "Preencha um telefone válido.",
  subject_label: "Assunto",
  subject_placeholder: "Assunto da mensagem",
  message_label: "Mensagem",
  message_placeholder: "Escreva sua mensagem…",
  form_submit_label: "Enviar mensagem",
  form_submitting_label: "Enviando…",
  form_success_message: "Em breve entrarei em contato.",
  form_error_message: "Não foi possível enviar. Tente novamente em instantes.",
  form_modal_success_title: "Mensagem enviada com sucesso!",
  form_modal_error_title: "Falha no envio",
  form_modal_processing_title: "Processando",
  form_modal_processing_message: "Processando mensagem",
  form_modal_close_label: "OK",
  form_debug_success_label: "Debug OK",
  form_debug_error_label: "Debug erro",
  form_config_missing_message:
    "Formulário ainda não configurado. Defina VITE_FORMSPREE_FORM_ID no arquivo .env.local.",
  },
  en: {
  title: "Let's talk? Get in touch with me",
  description:
    "Feel free to reach out to discuss collaboration opportunities, projects, or simply exchange ideas. I’m always open to meaningful connections and continuous learning opportunities.",
  phone_label: "Phone",
  phone: "+55 (92) 98415-8067",
  phone_href: "+5592984158067",
  phone_link: "+55 (92) 98415-8067",
  myEmail_label: "E-mail",
  myEmail: "emidioaranhadeveloper@gmail.com",
  myEmail_link: "emidioaranhadeveloper@gmail.com",
  linkedin_label: "LinkedIn",
  linkedin_url: "https://www.linkedin.com/in/emidio-aranha/",
  linkedin_link: "emidio-aranha",
  github_label: "GitHub",
  github: "https://github.com/EmidioAranha13",
  github_link: "EmidioAranha13",
  location_label: "Location",
  location: "Manaus, AM — Brazil",
  name_label: "Name",
  name_placeholder: "Your name",
  email_label: "E-mail",
  email_placeholder: "your@email.com",
  yourContact: "Your phone",
  yourContact_placeholder: "Your phone number",
  form_phone_invalid_message: "Please enter a valid phone number.",
  subject_label: "Subject",
  subject_placeholder: "Message subject",
  message_label: "Message",
  message_placeholder: "Write your message…",
  form_submit_label: "Send message",
  form_submitting_label: "Sending…",
  form_success_message: "Message sent successfully! I will get back to you soon.",
  form_error_message: "Could not send your message. Please try again shortly.",
  form_modal_success_title: "Sent successfully",
  form_modal_error_title: "Send failed",
  form_modal_processing_title: "Processing",
  form_modal_processing_message: "Processing message",
  form_modal_close_label: "OK",
  form_debug_success_label: "Debug OK",
  form_debug_error_label: "Debug error",
  form_config_missing_message:
    "Form is not configured yet. Set VITE_FORMSPREE_FORM_ID in your .env.local file.",
  },
  ja: {
  title: "お話ししませんか？",
  description:
    "コラボレーションの機会やプロジェクトの相談、またはアイデア交換など、お気軽にご連絡ください。新しいつながりや学びの機会をいつでも歓迎しています。",
  phone_label: "電話番号",
  phone: "+55 (92) 98415-8067",
  phone_href: "+5592984158067",
  phone_link: "+55 (92) 98415-8067",
  myEmail_label: "メール",
  myEmail: "emidioaranhadeveloper@gmail.com",
  myEmail_link: "emidioaranhadeveloper@gmail.com",
  linkedin_label: "LinkedIn",
  linkedin_url: "https://www.linkedin.com/in/emidio-aranha/",
  linkedin_link: "emidio-aranha",
  github_label: "GitHub",
  github: "https://github.com/EmidioAranha13",
  github_link: "EmidioAranha13",
  location_label: "所在地",
  location: "マナウス・AM — ブラジル",
  name_label: "名前",
  name_placeholder: "お名前",
  email_label: "メール",
  email_placeholder: "your@email.com",
  yourContact: "電話番号",
  yourContact_placeholder: "電話番号",
  form_phone_invalid_message: "有効な電話番号を入力してください。",
  subject_label: "件名",
  subject_placeholder: "メッセージの件名",
  message_label: "メッセージ",
  message_placeholder: "メッセージを入力してください…",
  form_submit_label: "メッセージを送信",
  form_submitting_label: "送信中…",
  form_success_message: "送信が完了しました。折り返しご連絡いたします。",
  form_error_message: "送信できませんでした。しばらくしてからもう一度お試しください。",
  form_modal_success_title: "送信完了",
  form_modal_error_title: "送信失敗",
  form_modal_processing_title: "処理中",
  form_modal_processing_message: "メッセージを処理中",
  form_modal_close_label: "OK",
  form_debug_success_label: "Debug OK",
  form_debug_error_label: "Debug エラー",
  form_config_missing_message:
    "フォームが未設定です。.env.local に VITE_FORMSPREE_FORM_ID を設定してください。",
  },
}
