export const experience_page = {
  br: {
  role_title: "Cargo",
  actions_title: "Atribuições",
  projects_title: "Projetos Relevantes",
  responsibility_title: "Responsabilidade",
  items: [
    {
      id: "delta",
      label: "Delta Sollutions",
      role: "Desenvolvedor Full Stack",
      time_working: "Maio 2025 - Atual",
      photos: [
        "photo1",
        "photo2",
        "delta_project_1",
        "delta_project_2",
        "delta_project_3",
        "delta_project_4",
        "delta_project_5",
        "delta_project_6",
        "delta_project_7",
        "delta_project_8",
        "delta_project_9",
        "delta_project_10",
        "delta_project_11",
        "delta_project_12",
      ],
      actions: [
        "Desenvolvimento de aplicações Web/Desktop utilizando React + Vite, React Router, Redux, Node.js, TypeScript, Material UI, Bootstrap e Styled Components",
        "Desenvolvimento de sistemas embarcados com ESP32 e Raspberry Pi (Pi OS) para aplicações industriais",
        "Implementação de soluções de Visão Computacional com Python + Open CV e integração com dispositivos industriais (Keyence)",
        "Definição e implementação de arquitetura de sistemas integrando IHM, MES e AWS",
        "Deploy e gerenciamento de aplicações com Docker, AWS e Python",
        "Integração, testes e acompanhamento de sistemas em ambiente industrial",
        "Manutenção e evolução de aplicações Desktop em C# para JIGs industriais",
        "Modelagem e manipulação de dados em MySQL, SQL Server e PostgreSQL (CRUD, queries e estruturação de tabelas)",
        "Desenvolvimento de Provas de Conceito (PoC) para validação de tecnologias e componentes; ",
        "Levantamento de requisitos e suporte à customização de soluções junto ao cliente",
        "Uso de Git (GitHub/GitLab) e ferramentas de gestão (Trello, Monday) com metodologias ágeis (Scrum/Kanban)",
        "Criação de mockups e interfaces (UX/UI) utilizando Figma",
        "Documentação técnica e treinamento de usuários finais",
        "Mentoria e onboarding de novos colaboradores, além de apoio em programas de capacitação",
      ],
      projects: [
        {
          project: "FCT (Functional Circuit Test) - Delta Bastidor JIG de Teste Personalizado",
          resume: "Sistema Automatizado para Testes de Placas Eletrônicas.",
          tasks_executed: "Encarregado de criar o software do jig desde o mockup à execução da programação frontend, backend, banco e comunicação com o firwmare em Raspberry Pi.",
        },
        {
          project: "Painel Eletrônico de Controle e Monitoramento",
          resume: "Projeto para aplicações industriais que exigem coleta de dados, monitoramento e controle preciso de processos.",
          tasks_executed: "Encarregado de criar o software do painel dashboard desde o mockup à execução da programação frontend, backend, banco e comunicação com MQTT Mosquito para transferência de dados via rede. Também responsável pela hospedagem da aplicação em AWS.",
        },
        {
          project: "Sistema de visão computacional personalizado para detecção de defeitos em componentes eletrônicos",
          resume: "Um sistema industrial composto por software e hardware voltado para julgamento de peças e componentes eletrônicos em linha de produção.",
          tasks_executed: "Responsável pela criação do software do sistema desde o mockup ao desenvolvimento do frontend, backend e comunicação via Modbus com o CLP delta que controla a automação do hardware. Também responsável pela lógica do julgamento da visão computacional mais treinamento e comunicação com o sistema de embarcados da Keyence (Câmera e softewre).",
        },
      ],
    },
    {
      id: "icts",
      label: "ICTS",
      role: "Desenvolvedor Web/Mobile Full Stack",
      time_working: "Setembro 2020 – Fevereiro 2024  ",
      photos: [],
      actions: [
        "Desenvolvimento de aplicações Web/Desktop utilizando React + Yarn, Redux, Node.js, PHP, TypeScript, Material UI, Bootstrap e Styled Components",
        "Desenvolvimento de aplicações Mobile para integração com os sistemas web em React Native e Android Studio",
        "Modelagem e manipulação de dados em MySQL, SQL Server e PostgreSQL (CRUD, queries e estruturação de tabelas)",
        "Produção de Provas de Conceito (PoC) para implementação de novas funcionalidades como ex: GraphQL para consulta em bancos e Spring Boot para facilitar criação de APIs",
        "Levantamento de requisitos e suporte à customização de soluções junto ao cliente",
        "Otimização da visualização e análise de dados com Python Pandas",
        "Manutenção e refatoração de sistemas legados",
        "Apoio na adaptação de novas tecnologias e boas práticas de desenvolvimento utilizando Trello como gerenciador e GitHub/GitLab para controle de versionamento e revisão de códigos", 
        "Atuação como mentor de novos colaboradores, auxiliando no onboarding técnico",
        "Participação em planejamentos com método Scrum + planning e Kanban",
        "Desenvolvimento e aplicação de melhorias em mockups",
      ],
      projects: [
        {
          project: "Sistema de Gerenciamento Empresarial Com Dashboard",
          resume: "Participação no desenvolvimento de um sistema de gerenciamento empresarial responsável por catalogar a entradas e saída de colaboradores, terceiros, visitas, veículos e materiais na portaria, na produção e refeitório. Além do espaço de monitoramento das linhas para identificação de somente pessoas autorizadas na produção, página de controle de produção diária e sistema mobile de suporte para registro de veículos e materiais.",
          tasks_executed: "Desenvolver o frontend Web e Mobile do sistema, Apis, e uma aplicação mobile auxiliar para registro de veículos e materiais.",
        },
        {
          project: "Sistema de Gerenciamento para Letreiros LED de Placas e Veículos",
          resume: "Participação no desenvolvimento de um sistema de cadastro e gerenciamento de mensagens para letreiros LED de placas para avisos e veículos sinalizadores (letreiros de ônibus por exemplo).",
          tasks_executed: "Responsável pela manutenção e evolução com acrescimo de novas funcionalidades e refatoração de código legado Frontend e Backend.",
        },
      ],
    },
    {
      id: "freelance",
      label: "Projetos Pessoais e Freelancers",
      role: "Desenvolvedor Freelancer",
      time_working: "Fevereiro 2024 - Abril 2025",
      photos: [],
      actions: [
        "Desenvolvimento de soluções sob demanda para clientes diversos.",
        "Criação de interfaces responsivas e integrações com APIs.",
        "Suporte pós-entrega e evolução de funcionalidades.",
        "Desenvolvimento de aplicações em Java, PHP com Laravel e Angular."
      ],
      projects: [
        {
          project: "Air Quality App",
          resume: "Projeto do DevTitans. Sistema embarcado com Android microcontrolador ESP32 e sensores para detecção de poluentes e gases no ar",
          tasks_executed: "Desenvolvimento da aplicação com Android Studio, Kotlin e Composer, desenvolvimento do mockup UX UI do sistema, integração com API do google Maps e salvamento dos dados no Firebase, conexão com a placa Esp32 e componentes de captação de qualidade do ar. Responsável pera direção e apresentação do projeto",
        },
        {
          project: "Icomp Números",
          resume: "Projeto de conclusão de curso. Software, em Node com Handlebars, de coleta de dados via upload de arquivos XML para gerenciamento de informações técnicas dos corpo docentes do ICOMP/UFAM. ",
          tasks_executed: "Desenvolvimento do Frontend e Backend do sistema e o tratamento de dados XML para parseamento dos campos na interface werb.",
        },
        {
          project: "MindTrack Agenda",
          resume: "Aplicação de gerenciamento de atividades psicológicas/psiquiátricas para acompanhamento pessoal e profissional aplicando LLM",
          tasks_executed: "Desenvolvimento do Frontend e Backend em Android Studio com Kotlin + composer e conexão com Llama para geração de respostas",
        },
        {
          project: "Sistema de Gerenciamento de PetShop",
          resume: "Sistema desktop em Java proposto para gerenciamento de atividades de um PetShop com consultas veterinárias, banho & tosa, e gerenciamento de materiais de venda.",
          tasks_executed: "Desenvolvimento do Frontend e Backend em Java com Swing para interface gráfica e conexão com banco de dados MySQL.",
        },
        // {
        //   project: "1",
        //   resume: "1",
        //   tasks_executed: "1",
        // }
      ],
    },
  ],
  },
  en: {
  role_title: "Role",
  actions_title: "Responsibilities",
  projects_title: "Relevant Projects",
  responsibility_title: "Responsabilities",
  items: [
    {
      id: "delta",
      label: "Delta Solutions",
      role: "Full Stack Developer",
      time_working: "May 2025 - Present",
      photos: [
        "photo1",
        "photo2",
        "delta_project_1",
        "delta_project_2",
        "delta_project_3",
        "delta_project_4",
        "delta_project_5",
        "delta_project_6",
        "delta_project_7",
        "delta_project_8",
        "delta_project_9",
        "delta_project_10",
        "delta_project_11",
        "delta_project_12",
      ],
      actions: [
        "Development of Web/Desktop applications using React + Vite, React Router, Redux, Node.js, TypeScript, Material UI, Bootstrap and Styled Components",
        "Development of embedded systems with ESP32 and Raspberry Pi (Pi OS) for industrial applications",
        "Implementation of Computer Vision solutions using Python + OpenCV and integration with industrial devices (Keyence)",
        "Definition and implementation of system architectures integrating HMI, MES and AWS",
        "Deployment and management of applications using Docker, AWS and Python",
        "Integration, testing and monitoring of systems in industrial environments",
        "Maintenance and evolution of Desktop applications in C# for industrial JIGs",
        "Data modeling and manipulation in MySQL, SQL Server and PostgreSQL (CRUD, queries and table structuring)",
        "Development of Proofs of Concept (PoC) for validation of technologies and components",
        "Requirements gathering and support for solution customization with clients",
        "Use of Git (GitHub/GitLab) and management tools (Trello, Monday) with agile methodologies (Scrum/Kanban)",
        "Creation of mockups and interfaces (UX/UI) using Figma",
        "Technical documentation and end-user training",
        "Mentoring and onboarding of new team members, as well as support in training programs",
      ],
      projects: [
        {
          project: "FCT (Functional Circuit Test) - Custom Test JIG Rack",
          resume: "Automated system for electronic board testing.",
          tasks_executed: "Responsible for developing the jig software from mockup to full implementation, including frontend, backend, database, and communication with firmware on Raspberry Pi.",
        },
        {
          project: "Electronic Control and Monitoring Panel",
          resume: "Industrial project focused on data collection, monitoring, and precise process control.",
          tasks_executed: "Responsible for developing the dashboard software from mockup to full implementation, including frontend, backend, database, and MQTT (Mosquitto) communication for data transfer. Also responsible for AWS deployment.",
        },
        {
          project: "Custom Computer Vision System for Defect Detection in Electronic Components",
          resume: "Industrial system combining software and hardware for inspection of electronic components in production lines.",
          tasks_executed: "Responsible for system development from mockup to frontend, backend, and Modbus communication with Delta PLC. Also handled vision logic, training, and integration with Keyence embedded system (camera and software).",
        },
      ],
    },
    {
      id: "icts",
      label: "ICTS",
      role: "Full Stack Web/Mobile Developer",
      time_working: "September 2020 – February 2024",
      photos: [],
      actions: [
        "Development of Web/Desktop applications using React + Yarn, Redux, Node.js, PHP, TypeScript, Material UI, Bootstrap and Styled Components",
        "Development of Mobile applications using React Native and Android Studio",
        "Data modeling and manipulation in MySQL, SQL Server and PostgreSQL (CRUD, queries and table structuring)",
        "Development of Proofs of Concept (PoC) for new technologies such as GraphQL and Spring Boot",
        "Requirements gathering and support for client customization",
        "Data analysis optimization using Python Pandas",
        "Maintenance and refactoring of legacy systems",
        "Support in adopting new technologies and best practices using Trello and GitHub/GitLab",
        "Mentoring new team members and technical onboarding",
        "Participation in planning using Scrum and Kanban",
        "Development and improvement of mockups",
      ],
      projects: [
        {
          project: "Enterprise Management System with Dashboard",
          resume: "Participation in the development of a system for managing employees, visitors, vehicles, and materials across different company areas, including production monitoring and mobile support.",
          tasks_executed: "Development of Web and Mobile frontend, APIs, and auxiliary mobile application.",
        },
        {
          project: "LED Display Management System",
          resume: "System for managing messages displayed on LED panels and vehicle signage.",
          tasks_executed: "Responsible for maintenance, feature implementation, and refactoring of frontend and backend systems.",
        },
      ],
    },
    {
      id: "freelance",
      label: "Personal Projects & Freelance",
      role: "Freelance Developer",
      time_working: "February 2024 - April 2025",
      photos: [],
      actions: [
        "Development of custom solutions for various clients",
        "Creation of responsive interfaces and API integrations",
        "Post-delivery support and feature evolution",
        "Development of applications using Java, PHP (Laravel), and Angular"
      ],
      projects: [
        {
          project: "Air Quality App",
          resume: "Embedded system project with ESP32 and sensors for air quality monitoring",
          tasks_executed: "Development using Android Studio, Kotlin and Composer, UX/UI design, Google Maps API integration, Firebase data storage, and ESP32 integration. Responsible for project leadership and presentation.",
        },
        {
          project: "Icomp Numbers",
          resume: "Final project: system for XML data processing and management of academic information",
          tasks_executed: "Frontend and backend development, XML parsing and data processing.",
        },
        {
          project: "MindTrack Agenda",
          resume: "Application for psychological/psychiatric activity management using LLM",
          tasks_executed: "Frontend and backend development using Kotlin and integration with Llama model.",
        },
        {
          project: "PetShop Management System",
          resume: "Desktop system for managing veterinary services and products",
          tasks_executed: "Development using Java Swing and MySQL database integration.",
        },
      ],
    },
  ],
  },
  ja: {
  role_title: "役職",
  actions_title: "職務内容",
  projects_title: "関連プロジェクト",
  responsibility_title: "職務内容",
  items: [
    {
      id: "delta",
      label: "デルタソリューションズ",
      role: "フルスタック開発者",
      time_working: "2025年5月 - 現在",
      photos: [
        "photo1",
        "photo2",
        "delta_project_1",
        "delta_project_2",
        "delta_project_3",
        "delta_project_4",
        "delta_project_5",
        "delta_project_6",
        "delta_project_7",
        "delta_project_8",
        "delta_project_9",
        "delta_project_10",
        "delta_project_11",
        "delta_project_12",
      ],
      actions: [
        "React + Vite、React Router、Redux、Node.js、TypeScript、Material UI、Bootstrap、Styled Componentsを使用したWeb/デスクトップアプリの開発",
        "ESP32およびRaspberry Pi（Pi OS）を用いた組み込みシステムの開発",
        "Python + OpenCVによる画像処理ソリューションの実装と産業機器（Keyence）との連携",
        "HMI、MES、AWSを統合したシステムアーキテクチャの設計と実装",
        "Docker、AWS、Pythonを使用したデプロイおよび運用管理",
        "産業環境でのシステム統合、テスト、監視",
        "C#による産業用JIG向けデスクトップアプリの保守と改善",
        "MySQL、SQL Server、PostgreSQLでのデータ設計および操作（CRUD、クエリ、テーブル設計）",
        "技術検証のためのPoC（概念実証）の開発",
        "要件定義および顧客向けカスタマイズ対応",
        "Git（GitHub/GitLab）やTrello、Mondayを使用したアジャイル開発（Scrum/Kanban）",
        "Figmaを用いたUI/UX設計とモックアップ作成",
        "技術ドキュメント作成およびユーザー教育",
        "新メンバーの指導およびオンボーディング支援",
      ],
      projects: [
        {
          project: "FCT（機能回路テスト）カスタムJIGシステム",
          resume: "電子基板テストのための自動化システム",
          tasks_executed: "モックアップからフロントエンド、バックエンド、データベース、Raspberry Piとの通信までシステム全体を開発",
        },
        {
          project: "電子制御・監視パネル",
          resume: "データ収集、監視、制御を行う産業向けシステム",
          tasks_executed: "ダッシュボードの開発（フロント・バックエンド・DB）およびMQTT通信の実装とAWSへのデプロイ",
        },
        {
          project: "電子部品の欠陥検出用画像処理システム",
          resume: "生産ラインで部品検査を行う産業システム",
          tasks_executed: "フロント・バックエンド開発およびModbus通信、画像処理ロジック、Keyence機器との連携",
        },
      ],
    },
    {
      id: "icts",
      label: "ICTS",
      role: "フルスタックWeb/モバイル開発者",
      time_working: "2020年9月 - 2024年2月",
      photos: [],
      actions: [
        "React、Redux、Node.js、PHPなどを用いたWeb/デスクトップアプリ開発",
        "React NativeおよびAndroid Studioによるモバイルアプリ開発",
        "データベース設計および操作（MySQL、SQL Server、PostgreSQL）",
        "GraphQLやSpring Bootなどの技術検証（PoC）",
        "要件定義および顧客対応",
        "Python Pandasによるデータ分析の最適化",
        "レガシーシステムの保守およびリファクタリング",
        "新技術導入のサポートとベストプラクティスの適用",
        "新メンバーの指導および技術オンボーディング",
        "ScrumやKanbanによる開発計画への参加",
        "UI改善およびモックアップの作成",
      ],
      projects: [
        {
          project: "企業管理システム（ダッシュボード付き）",
          resume: "従業員や車両、資材などを管理するシステムの開発",
          tasks_executed: "Web・モバイルフロントエンドおよびAPIの開発",
        },
        {
          project: "LED表示管理システム",
          resume: "LED表示メッセージの管理システム",
          tasks_executed: "機能追加およびフロント・バックエンドの改善",
        },
      ],
    },
    {
      id: "freelance",
      label: "個人プロジェクトとフリーランス",
      role: "フリーランス開発者",
      time_working: "2024年2月 - 2025年4月",
      photos: [],
      actions: [
        "クライアント向けカスタムシステムの開発",
        "レスポンシブUIおよびAPI連携の実装",
        "納品後のサポートと機能改善",
        "Java、PHP（Laravel）、Angularでの開発"
      ],
      projects: [
        {
          project: "Air Quality App",
          resume: "ESP32とセンサーを用いた空気品質監視システム",
          tasks_executed: "Android Studio（Kotlin）での開発、UI設計、Firebase連携、ESP32通信の実装",
        },
        {
          project: "Icomp Numbers",
          resume: "XMLデータ管理システム",
          tasks_executed: "フロント・バックエンド開発およびXMLデータ処理",
        },
        {
          project: "MindTrack Agenda",
          resume: "心理・精神活動管理アプリ（LLM活用）",
          tasks_executed: "Kotlinでの開発およびLLM連携",
        },
        {
          project: "ペットショップ管理システム",
          resume: "ペットショップ業務管理用デスクトップアプリ",
          tasks_executed: "Java SwingとMySQLを使用した開発",
        },
      ],
    },
  ],
  },
}
