export const globals = {
  br: {
    name: "Emídio Aranha",
    role: "Desenvolvedor Full Stack | Soluções Web, Mobile & IoT",
    about: "Sobre mim",
    education: "Formação",
    experience: "Experiências",
    skills: "Habilidades",
    certifications: "Certificações",
    projects: "Projetos",
    contact: "Contatos",
    downloadCV: "Baixar Currículo",
    contactMe: "Contate-me",
    cv_filename: "Emídio Aranha - Currículo Desenvolvedor Web FullStack.pdf",
    techStack: "React + React Native | Android | Angular | PHP | IA",
    footerRights: "Emídio Aranha - 2026. Todos os direitos reservados.",
  },
  en: {
    name: "Emídio Aranha",
    role: "Full Stack Developer | Web, Mobile & IoT Solutions",
    about: "About me",
    education: "Education",
    experience: "Experience",
    skills: "Skills",
    certifications: "Certifications",
    projects: "Projects",
    contact: "Contact",
    downloadCV: "Download Curriculum",
    contactMe: "Contact me",
    cv_filename: "Emídio Aranha - Currículo Desenvolvedor Web FullStack.pdf",
    techStack: "React + React Native | Android | Angular | PHP | AI",
    footerRights: "Emídio Aranha - 2026. All rights reserved.",
  },
  ja: {
    name: "エミジオ・アラーニャ",
    role: "フルスタック開発者｜Web・モバイル・IoT",
    about: "プロフィール",
    education: "学習・経歴",
    experience: "経験",
    skills: "スキル",
    certifications: "資格・認定",
    projects: "制作実績",
    contact: "コンタクト",
    downloadCV: "CVをダウンロード",
    contactMe: "気軽に連絡してください",
    cv_filename: "Emídio Aranha - Currículo Desenvolvedor Web FullStack.pdf",
    techStack: "React／React Native｜Android｜Angular｜PHP｜AI",
    footerRights: "エミジオ・アラーニャ - 2026. All rights reserved.",
  },
}
