import { PROJECTS_BR, PROJECTS_EN, PROJECTS_JA } from "./shared/projectsData";

export const projects_page = {
  br: {
  contributions_title: "Contribuições no GitHub",
  my_projects_title: "Sistemas Desenvolvidos",
  my_projects_placeholder: "Em breve: lista de projetos.",
  contributions_total: "{{count}} contribuições no último ano",
  contributions_less: "Menos",
  contributions_more: "Mais",
  contributions_error: "Não foi possível carregar as contribuições do GitHub.",
  contributions_calendar_loading_label: "Carregando contribuições do GitHub",
  github_profile_label: "Ver perfil @EmidioAranha13",
  stat_total_label: "Projetos no Total",
  stat_completed_label: "Projetos Completos",
  stat_personal_label: "Projetos Pessoais",
  stat_in_progress_label: "Em Andamento",
  carousel_prev_label: "Projeto anterior",
  carousel_next_label: "Próximo projeto",
  carousel_aria_label: "Carrossel de projetos",
  carousel_learn_more_label: "Saiba mais",
  carousel_summary_label: "Resumo do Projeto",
  project_modal_close_label: "Fechar",
  project_modal_screens_web_label: "Telas Web",
  project_modal_screens_mobile_label: "Telas Mobile",
  project_modal_screens_empty_label: "Não foram encontradas imagens para a sessão.",
  project_modal_screen_prev_label: "Tela anterior",
  project_modal_screen_next_label: "Próxima tela",
  project_modal_github_label: "GitHub",
  project_modal_live_label: "Testar",
  project_modal_technologies_label: "Tecnologias: ",
  projects: PROJECTS_BR,
  stats: {
    total: 12,
    completed: 6,
    personal: 4,
    in_progress: 1,
  },
  },
  en: {
  contributions_title: "GitHub contributions",
  my_projects_title: "Developed Systems",
  my_projects_placeholder: "Coming soon: project list.",
  contributions_total: "{{count}} contributions in the last year",
  contributions_less: "Less",
  contributions_more: "More",
  contributions_error: "Could not load GitHub contributions.",
  contributions_calendar_loading_label: "Loading GitHub contributions",
  github_profile_label: "View profile @EmidioAranha13",
  stat_total_label: "Total Projects",
  stat_completed_label: "Completed Projects",
  stat_personal_label: "Personal Projects",
  stat_in_progress_label: "In Progress",
  carousel_prev_label: "Previous project",
  carousel_next_label: "Next project",
  carousel_aria_label: "Projects carousel",
  carousel_learn_more_label: "Learn more",
  carousel_summary_label: "Project Summary",
  project_modal_close_label: "Close",
  project_modal_screens_web_label: "Web Screens",
  project_modal_screens_mobile_label: "Mobile Screens",
  project_modal_screens_empty_label: "No images were found for this section.",
  project_modal_screen_prev_label: "Previous screen",
  project_modal_screen_next_label: "Next screen",
  project_modal_github_label: "GitHub",
  project_modal_live_label: "Try it",
  project_modal_technologies_label: "Technologies: ",
  projects: PROJECTS_EN,
  stats: {
    total: 12,
    completed: 6,
    personal: 4,
    in_progress: 1,
  },
  },
  ja: {
  contributions_title: "GitHub コントリビューション",
  my_projects_title: "開発実績",
  my_projects_placeholder: "近日公開：プロジェクト一覧。",
  contributions_total: "過去1年で {{count}} 件のコントリビューション",
  contributions_less: "少",
  contributions_more: "多",
  contributions_error: "GitHub のコントリビューションを読み込めませんでした。",
  contributions_calendar_loading_label: "GitHub のコントリビューションを読み込み中",
  github_profile_label: "プロフィール @EmidioAranha13 を見る",
  stat_total_label: "プロジェクト総数",
  stat_completed_label: "完了プロジェクト",
  stat_personal_label: "個人プロジェクト",
  stat_in_progress_label: "進行中",
  carousel_prev_label: "前のプロジェクト",
  carousel_next_label: "次のプロジェクト",
  carousel_aria_label: "プロジェクトカルーセル",
  carousel_learn_more_label: "詳しく見る",
  carousel_summary_label: "プロジェクト概要",
  project_modal_close_label: "閉じる",
  project_modal_screens_web_label: "Web画面",
  project_modal_screens_mobile_label: "モバイル画面",
  project_modal_screens_empty_label: "このセクションの画像が見つかりませんでした。",
  project_modal_screen_prev_label: "前の画面",
  project_modal_screen_next_label: "次の画面",
  project_modal_github_label: "GitHub",
  project_modal_live_label: "試す",
  project_modal_technologies_label: "技術: ",
  projects: PROJECTS_JA,
  stats: {
    total: 12,
    completed: 6,
    personal: 4,
    in_progress: 1,
  },
  },
}
