import type { SkillPageSkill } from "../Types";

export const skill_page = {
  br: {
  experience_label: "Experiência:",
  projects_label: "Em projetos:",
  filter_aria_label: "Filtrar por linha de frente",
  filter_icon_alt: "Filtro",
  search_placeholder: "Pesquisar habilidade...",
  search_aria_label: "Pesquisar habilidade",
  listed_items_label: "Itens Listados: {{count}}",
  empty_message: "Nenhum item encontrado",
  grid_aria_label: "Cards de habilidades",
  filter_options: {
    all: "Todas",
    frontend: "Frontend",
    backend: "Backend",
    mobile: "Mobile",
    devops: "DevOps",
    design: "Design",
    management: "Management",
    database: "Database",
    tools: "Tools",
  },
  skills: [
    {
      title: "React",
      description: "Biblioteca para construção de interfaces dinâmicas baseada em componentes, utilizando tanto classes quanto Hooks para gerenciamento de estado e ciclo de vida.",
      years: "5 ano",
      projects: "11",
      img: "",
      badges: ["react"],
      types: ["frontend"],
    },
    {
      title: "React Native + Expo",
      description: "Framework para desenvolvimento de aplicativos móveis nativos utilizando JavaScript/TypeScript e a mesma lógica baseada em componentes do React.",
      years: "5 ano",
      projects: "3",
      img: "",
      badges: ["react_native"],
      types: ["frontend", "mobile"],
    },
    {
      title: "JavaScript + TypeScript",
      description: "Linguagens utilizadas que atuam na construção de interfaces interativas no frontend e também na lógica de negócio no backend.",
      years: "5 ano",
      projects: "12",
      img: "",
      badges: ["typescript", "javascript"],
      types: ["frontend", "backend"],
    },
    {
      title: "Redux",
      description: "Biblioteca de gerenciamento de estado global que centraliza e organiza os dados da aplicação de forma previsível. Modelos trabalhados: Thunk, Saga, RTK Query.",
      years: "5 ano",
      projects: "6",
      img: "",
      badges: ["redux"],
      types: ["frontend"],
    },
    {
      title: "HTML",
      description: "Linguagem de marcação utilizada para estruturar o conteúdo e os elementos de páginas web.",
      years: "5 ano",
      projects: "6",
      img: "",
      badges: ["html"],
      types: ["frontend"],
    },
    {
      title: "CSS",
      description: "Linguagem de estilos responsável pela aparência, layout e responsividade das interfaces web.",
      years: "5 ano",
      projects: "6",
      img: "",
      badges: ["css"],
      types: ["frontend"],
    },
    {
      title: "Material UI",
      description: "Biblioteca de componentes React que implementa o design system Material Design para criação rápida de interfaces modernas e consistentes.",
      years: "5 ano",
      projects: "3",
      img: "",
      badges: ["material_ui"],
      types: ["frontend"],
    },
    {
      title: "Bootstrap",
      description: "Framework CSS que facilita a criação de interfaces web responsivas e consistentes, com uma ampla gama de componentes pré-construídos.",
      years: "5 ano",
      projects: "6",
      img: "",
      badges: ["bootstrap"],
      types: ["frontend"],
    },
    {
      title: "Handlebars",
      description: "Template engine para geração dinâmica de HTML no backend a partir de dados estruturados.",
      years: "1",
      projects: "1",
      img: "",
      badges: ["handlebars"],
      types: ["frontend", "backend"],
    },
    {
      title: "Style Dictionary",
      description: "Ferramenta para gerenciamento e padronização de design tokens entre diferentes plataformas.",
      years: "2",
      projects: "3",
      img: "",
      badges: ["style_dictionary"],
      types: ["frontend"],
    },
    {
      title: "Unstyled Components",
      description: "Abordagem de componentes desacoplados de estilo, permitindo total controle visual via CSS ou outras bibliotecas.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["styled_components"],
      types: ["frontend"],
    },
    {
      title: "Node.js",
      description: "Ambiente de execução JavaScript no servidor utilizado para construção de aplicações backend escaláveis.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["node"],
      types: ["backend"],
    },
    {
      title: "Express",
      description: "Framework minimalista para Node.js utilizado na criação de APIs e aplicações web.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["express"],
      types: ["backend"],
    },
    {
      title: "Sequelize",
      description: "ORM para Node.js que facilita a comunicação e manipulação de bancos de dados relacionais.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["sequelize"],
      types: ["backend", "database"],
    },
    {
      title: "API REST",
      description: "Arquitetura para desenvolvimento de APIs baseada em requisições HTTP e comunicação padronizada entre sistemas.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["rest_api"],
      types: ["backend"],
    },
    {
      title: "GraphQL",
      description: "Linguagem de consulta para APIs que permite solicitar exatamente os dados necessários de forma eficiente.",
      years: "1",
      projects: "1",
      img: "",
      badges: ["graphql"],
      types: ["backend"],
    },
    {
      title: "Spring Boot",
      description: "Framework Java para criação rápida de aplicações backend robustas e escaláveis.",
      years: "1",
      projects: "1",
      img: "",
      badges: ["spring_boot"],
      types: ["backend"],
    },
    {
      title: "Docker",
      description: "Plataforma de containerização que permite empacotar e executar aplicações de forma isolada e consistente.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["docker"],
      types: ["devops"],
    },
    {
      title: "AWS",
      description: "Plataforma de serviços em nuvem utilizada para deploy, armazenamento e escalabilidade de aplicações.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["aws"],
      types: ["devops"],
    },
    {
      title: "Figma",
      description: "Ferramenta de design colaborativo para criação de interfaces, protótipos e sistemas de design.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["figma"],
      types: ["design"],
    },
    {
      title: "SQL",
      description: "Linguagem padrão para consulta, manipulação e gerenciamento de bancos de dados relacionais.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["sql"],
      types: ["database"],
    },
    {
      title: "MySQL",
      description: "Sistema de gerenciamento de banco de dados relacional amplamente utilizado em aplicações web.",
      years: "5",
      projects: "6",
      img: "",  
      badges: ["mysql"],
      types: ["database"],
    },
    {
      title: "MSSQL",
      description: "Sistema de banco de dados relacional da Microsoft utilizado em aplicações corporativas.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["mssql"],
      types: ["database"],
    },
    {
      title: "PostgreSQL",
      description: "Banco de dados relacional avançado, conhecido por sua robustez e suporte a consultas complexas.",
      years: "5",
      projects: "6  ",
      img: "",
      badges: ["postgresql"],
      types: ["database"],
    },
    {
      title: "Android Studio",
      description: "Ambiente de desenvolvimento oficial para criação de aplicações Android.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["android_studio"],
      types: ["mobile", "tools"],
    },
    {
      title: "Kotlin",
      description: "Linguagem moderna utilizada no desenvolvimento Android, interoperável com Java e focada em concisão e segurança.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["kotlin"],
      types: ["mobile", "backend"],
    },
    {
      title: "Jetpack Compose",
      description: "Toolkit moderno para construção de interfaces Android de forma declarativa.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["jetpack_compose"],
      types: ["mobile"],
    },
    {
      title: "Java",
      description: "Linguagem de programação orientada a objetos amplamente utilizada em sistemas corporativos e Android.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["java"],
      types: ["backend", "mobile"],
    },
    {
      title: "C / C++ / C#",
      description: "Conjunto de linguagens utilizadas para desenvolvimento de sistemas de baixo nível, aplicações performáticas e software corporativo.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["c_family"],
      types: ["backend"],
    },
    {
      title: "Rust",
      description: "Linguagem focada em segurança de memória e alta performance para sistemas críticos.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["rust"],
      types: ["backend"],
    },
    {
      title: "Python",
      description: "Linguagem versátil utilizada em automação, análise de dados, backend e inteligência artificial.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["python"],
      types: ["backend"],
    },
    {
      title: "Git (GitHub/GitLab)",
      description: "Sistema de controle de versão distribuído para gerenciamento de código e colaboração em equipe.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["git_github"],
      types: ["tools", "devops"],
    },
    {
      title: "BPMN",
      description: "Notação gráfica para modelagem e documentação de processos de negócio.",
      years: "5",
      projects: "6 ",
      img: "",
      badges: ["bpmn"],
      types: ["management"],
    },
    {
      title: "UML",
      description: "Linguagem de modelagem utilizada para representar a estrutura e o comportamento de sistemas.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["uml"],
      types: ["management"],
    },
    {
      title: "Storybook",
      description: "Ferramenta para desenvolvimento e documentação isolada de componentes de interface.",
      years: "5",
      projects: "6",
      img: "",
      badges: ["storybook"],
      types: ["frontend"],
    },
    {
      title: "Data Analysis with Python",
      description: "Uso de Python para análise, processamento e visualização de dados.",
      years: "5",   
      projects: "6",
      img: "",    
      badges: ["pandas"],
      types: ["backend"],
    },
    {
      title: "Jest (Testing)",
      description: "Framework de testes para JavaScript utilizado para garantir qualidade e confiabilidade do código.",
      years: "5",
      projects: "6",
      img: "",  
      badges: ["jest"],
      types: ["frontend", "backend"],
    },
    {
      title: "Vite",
      description: "Build tool e servidor de desenvolvimento para aplicações web modernas, com HMR rápido e empacotamento otimizado para produção.",
      years: "3",
      projects: "0",
      img: "",
      badges: ["vite"],
      types: ["frontend"],
    },
    {
      title: "Yarn",
      description: "Gerenciador de pacotes rápido e confiável para dependências JavaScript, com lockfile determinístico.",
      years: "5",
      projects: "0",
      img: "",
      badges: ["yarn"],
      types: ["tools"],
    },
    {
      title: "Agile Methodologies (Scrum, Kanban, BDD)",
      description: "Metodologias ágeis para gerenciamento de projetos com foco em entrega contínua e colaboração.",
      years: "5",
      projects: "6 ",
      img: "",
      badges: ["agile"],
      types: ["management"],
    },
  ] satisfies SkillPageSkill[],
  },
  en: {
  experience_label: "Experience:",
  projects_label: "In projects:",
  filter_aria_label: "Filter by stack line",
  filter_icon_alt: "Filter",
  search_placeholder: "Search skill...",
  search_aria_label: "Search skill",
  listed_items_label: "Listed items: {{count}}",
  empty_message: "No items found",
  grid_aria_label: "Skill cards",
  filter_options: {
    all: "All",
    frontend: "Frontend",
    backend: "Backend",
    mobile: "Mobile",
    devops: "DevOps",
    design: "Design",
    management: "Management",
    database: "Database",
    tools: "Tools",
  },
  skills: [
    {
      title: "React",
      description: "Component-based library for building scalable and highly interactive user interfaces, leveraging both class-based architecture and modern Hooks for state and lifecycle management.",
      years: "5 years",
      projects: "11",
      img: "",
      badges: ["react"],
      types: ["frontend"],
    },
    {
      title: "React Native + Expo",
      description: "Framework for developing cross-platform native mobile applications using JavaScript/TypeScript with React’s declarative component architecture.",
      years: "5 years",
      projects: "3",
      img: "",
      badges: ["react_native"],
      types: ["frontend", "mobile"],
    },
    {
      title: "JavaScript + TypeScript",
      description: "Core languages used to build dynamic frontend experiences and scalable backend business logic with strong typing and modern ECMAScript standards.",
      years: "5 years",
      projects: "12",
      img: "",
      badges: ["typescript", "javascript"],
      types: ["frontend", "backend"],
    },
    {
      title: "Redux",
      description: "Predictable global state management library designed to centralize and orchestrate application data efficiently. Experienced with Thunk, Saga, and RTK Query patterns.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["redux"],
      types: ["frontend"],
    },
    {
      title: "HTML",
      description: "Standard markup language used to structure semantic content and define the foundation of modern web applications.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["html"],
      types: ["frontend"],
    },
    {
      title: "CSS",
      description: "Styling language responsible for visual presentation, responsive layouts, animations, and user interface consistency across platforms.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["css"],
      types: ["frontend"],
    },
    {
      title: "Material UI",
      description: "React component library implementing Google’s Material Design system for rapidly building polished and accessible interfaces.",
      years: "5 years",
      projects: "3",
      img: "",
      badges: ["material_ui"],
      types: ["frontend"],
    },
    {
      title: "Bootstrap",
      description: "Responsive CSS framework offering reusable UI components and layout utilities for fast and consistent web development.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["bootstrap"],
      types: ["frontend"],
    },
    {
      title: "Handlebars",
      description: "Template engine used for dynamic HTML generation on the backend through structured and reusable data rendering.",
      years: "1 year",
      projects: "1",
      img: "",
      badges: ["handlebars"],
      types: ["frontend", "backend"],
    },
    {
      title: "Style Dictionary",
      description: "Tool designed for managing and synchronizing design tokens consistently across multiple platforms and design systems.",
      years: "2 years",
      projects: "3",
      img: "",
      badges: ["style_dictionary"],
      types: ["frontend"],
    },
    {
      title: "Unstyled Components",
      description: "Approach focused on decoupling logic from styling, enabling complete visual customization through CSS or alternative styling solutions.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["styled_components"],
      types: ["frontend"],
    },
    {
      title: "Node.js",
      description: "Server-side JavaScript runtime environment used to build scalable, event-driven, and high-performance backend applications.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["node"],
      types: ["backend"],
    },
    {
      title: "Express",
      description: "Minimalist Node.js framework widely adopted for building RESTful APIs and robust web server architectures.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["express"],
      types: ["backend"],
    },
    {
      title: "Sequelize",
      description: "ORM for Node.js that simplifies relational database modeling, querying, and data manipulation through abstraction layers.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["sequelize"],
      types: ["backend", "database"],
    },
    {
      title: "API REST",
      description: "Architectural style for designing scalable APIs using standardized HTTP communication principles between distributed systems.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["rest_api"],
      types: ["backend"],
    },
    {
      title: "GraphQL",
      description: "Query language for APIs enabling clients to retrieve precisely the required data with optimized and flexible requests.",
      years: "1 year",
      projects: "1",
      img: "",
      badges: ["graphql"],
      types: ["backend"],
    },
    {
      title: "Spring Boot",
      description: "Java-based framework for rapidly building enterprise-grade backend services and scalable microservice architectures.",
      years: "1 year",
      projects: "1",
      img: "",
      badges: ["spring_boot"],
      types: ["backend"],
    },
    {
      title: "Docker",
      description: "Containerization platform used to package, isolate, and deploy applications consistently across different environments.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["docker"],
      types: ["devops"],
    },
    {
      title: "AWS",
      description: "Cloud computing platform utilized for infrastructure provisioning, scalable deployments, storage solutions, and application hosting.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["aws"],
      types: ["devops"],
    },
    {
      title: "Figma",
      description: "Collaborative interface design tool used for prototyping, design systems, wireframing, and user experience workflows.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["figma"],
      types: ["design"],
    },
    {
      title: "SQL",
      description: "Standard query language used for managing, manipulating, and retrieving data from relational database systems.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["sql"],
      types: ["database"],
    },
    {
      title: "MySQL",
      description: "Widely adopted relational database management system commonly used in scalable and data-driven web applications.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["mysql"],
      types: ["database"],
    },
    {
      title: "MSSQL",
      description: "Microsoft’s enterprise-grade relational database solution designed for high-performance corporate applications and analytics.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["mssql"],
      types: ["database"],
    },
    {
      title: "PostgreSQL",
      description: "Advanced open-source relational database recognized for reliability, extensibility, and support for complex queries.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["postgresql"],
      types: ["database"],
    },
    {
      title: "Android Studio",
      description: "Official integrated development environment for building, testing, and deploying Android applications.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["android_studio"],
      types: ["mobile", "tools"],
    },
    {
      title: "Kotlin",
      description: "Modern programming language for Android development focused on conciseness, interoperability, and type safety.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["kotlin"],
      types: ["mobile", "backend"],
    },
    {
      title: "Jetpack Compose",
      description: "Modern declarative UI toolkit for Android development designed to simplify interface creation and state handling.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["jetpack_compose"],
      types: ["mobile"],
    },
    {
      title: "Java",
      description: "Object-oriented programming language extensively used in enterprise systems, backend services, and Android ecosystems.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["java"],
      types: ["backend", "mobile"],
    },
    {
      title: "C / C++ / C#",
      description: "Collection of programming languages applied to low-level systems, high-performance applications, and enterprise-grade software solutions.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["c_family"],
      types: ["backend"],
    },
    {
      title: "Rust",
      description: "Systems programming language focused on memory safety, concurrency, and high-performance software development.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["rust"],
      types: ["backend"],
    },
    {
      title: "Python",
      description: "Versatile programming language commonly used in automation, backend systems, artificial intelligence, and data analysis.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["python"],
      types: ["backend"],
    },
    {
      title: "Git (GitHub/GitLab)",
      description: "Distributed version control system used for source code management, collaboration workflows, and repository maintenance.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["git_github"],
      types: ["tools", "devops"],
    },
    {
      title: "BPMN",
      description: "Graphical notation standard used for modeling, documenting, and optimizing business process workflows.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["bpmn"],
      types: ["management"],
    },
    {
      title: "UML",
      description: "Modeling language used to visually represent software architecture, system behavior, and object-oriented structures.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["uml"],
      types: ["management"],
    },
    {
      title: "Storybook",
      description: "Development environment for building, testing, and documenting isolated UI components in scalable frontend applications.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["storybook"],
      types: ["frontend"],
    },
    {
      title: "Data Analysis with Python",
      description: "Utilization of Python libraries for data processing, analysis, visualization, and transformation workflows.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["pandas"],
      types: ["backend"],
    },
    {
      title: "Jest (Testing)",
      description: "JavaScript testing framework used for unit and integration testing to ensure code reliability and maintainability.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["jest"],
      types: ["frontend", "backend"],
    },
    {
      title: "Vite",
      description: "Fast build tool and dev server for modern web applications, with instant HMR and optimized production bundling.",
      years: "3 years",
      projects: "0",
      img: "",
      badges: ["vite"],
      types: ["frontend"],
    },
    {
      title: "Yarn",
      description: "Fast and reliable JavaScript package manager with deterministic lockfiles, used as an alternative to npm.",
      years: "5 years",
      projects: "0",
      img: "",
      badges: ["yarn"],
      types: ["tools"],
    },
    {
      title: "Agile Methodologies (Scrum, Kanban, BDD)",
      description: "Agile project management methodologies focused on iterative delivery, collaboration, adaptability, and continuous improvement.",
      years: "5 years",
      projects: "6",
      img: "",
      badges: ["agile"],
      types: ["management"],
    },
  ] satisfies SkillPageSkill[],
  },
  ja: {
  experience_label: "経験:",
  projects_label: "プロジェクト:",
  filter_aria_label: "スタックで絞り込む",
  filter_icon_alt: "フィルター",
  search_placeholder: "スキルを検索...",
  search_aria_label: "スキルを検索",
  listed_items_label: "表示件数: {{count}}",
  empty_message: "該当する項目がありません",
  grid_aria_label: "スキルカード",
  filter_options: {
    all: "すべて",
    frontend: "フロントエンド",
    backend: "バックエンド",
    mobile: "モバイル",
    devops: "DevOps",
    design: "デザイン",
    management: "マネジメント",
    database: "データベース",
    tools: "ツール",
  },
  skills: [
    {
      title: "React",
      description: "コンポーネントベースで動的なユーザーインターフェースを構築するためのライブラリです。状態管理やライフサイクルの制御にクラスとHooksの両方を使用できます。",
      years: "5年",
      projects: "11",
      img: "",
      badges: ["react"],
      types: ["frontend"],
    },
    {
      title: "React Native + Expo",
      description: "JavaScript/TypeScriptとReactのコンポーネントベースの考え方を利用して、ネイティブモバイルアプリを開発するためのフレームワークです。",
      years: "5年",
      projects: "3",
      img: "",
      badges: ["react_native"],
      types: ["frontend", "mobile"],
    },
    {
      title: "JavaScript + TypeScript",
      description: "フロントエンドのインタラクティブなUI構築や、バックエンドのビジネスロジック開発に使用されるプログラミング言語です。",
      years: "5年",
      projects: "12",
      img: "",
      badges: ["typescript", "javascript"],
      types: ["frontend", "backend"],
    },
    {
      title: "Redux",
      description: "アプリケーションのデータを一元管理し、予測可能な形で状態を管理するためのライブラリです。Thunk、Saga、RTK Queryを利用した経験があります。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["redux"],
      types: ["frontend"],
    },
    {
      title: "HTML",
      description: "Webページのコンテンツや要素の構造を定義するためのマークアップ言語です。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["html"],
      types: ["frontend"],
    },
    {
      title: "CSS",
      description: "Webインターフェースの見た目、レイアウト、レスポンシブデザインを担当するスタイルシート言語です。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["css"],
      types: ["frontend"],
    },
    {
      title: "Material UI",
      description: "Material Designを実装したReactコンポーネントライブラリで、モダンで統一感のあるUIを素早く構築できます。",
      years: "5年",
      projects: "3",
      img: "",
      badges: ["material_ui"],
      types: ["frontend"],
    },
    {
      title: "Bootstrap",
      description: "レスポンシブで一貫性のあるWebインターフェースを効率的に作成できるCSSフレームワークです。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["bootstrap"],
      types: ["frontend"],
    },
    {
      title: "Handlebars",
      description: "構造化されたデータを利用して、バックエンドで動的にHTMLを生成するためのテンプレートエンジンです。",
      years: "1年",
      projects: "1",
      img: "",
      badges: ["handlebars"],
      types: ["frontend", "backend"],
    },
    {
      title: "Style Dictionary",
      description: "異なるプラットフォーム間でデザイントークンを管理・標準化するためのツールです。",
      years: "2年",
      projects: "3",
      img: "",
      badges: ["style_dictionary"],
      types: ["frontend"],
    },
    {
      title: "Unstyled Components",
      description: "スタイルを分離したコンポーネント設計の手法で、CSSや他のライブラリを使って自由にデザインできます。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["styled_components"],
      types: ["frontend"],
    },
    {
      title: "Storybook",
      description: "UIコンポーネントを独立して開発・テスト・ドキュメント化するためのツールです。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["storybook"],
      types: ["frontend"],
    },
    {
      title: "Vite",
      description: "高速なHMRと最適化されたビルド機能を提供する、モダンなWebアプリ向けの開発サーバーおよびビルドツールです。",
      years: "3年",
      projects: "0",
      img: "",
      badges: ["vite"],
      types: ["frontend"],
    },
    {
      title: "Node.js",
      description: "サーバーサイドでJavaScriptを実行し、スケーラブルなバックエンドアプリケーションを開発するための実行環境です。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["node"],
      types: ["backend"],
    },
    {
      title: "Express",
      description: "Node.js向けの軽量なフレームワークで、APIやWebアプリケーションの開発に使用されます。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["express"],
      types: ["backend"],
    },
    {
      title: "Sequelize",
      description: "Node.js向けのORMで、リレーショナルデータベースとの連携やデータ操作を簡単に行うことができます。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["sequelize"],
      types: ["backend", "database"],
    },
    {
      title: "API REST",
      description: "HTTPリクエストを利用してシステム間で標準化された通信を行うためのAPIアーキテクチャです。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["rest_api"],
      types: ["backend"],
    },
    {
      title: "GraphQL",
      description: "必要なデータのみを効率的に取得できるAPI向けのクエリ言語です。",
      years: "1年",
      projects: "1",
      img: "",
      badges: ["graphql"],
      types: ["backend"],
    },
    {
      title: "Spring Boot",
      description: "堅牢で拡張性の高いバックエンドアプリケーションを迅速に開発するためのJavaフレームワークです。",
      years: "1年",
      projects: "1",
      img: "",
      badges: ["spring_boot"],
      types: ["backend"],
    },
    {
      title: "Java",
      description: "オブジェクト指向プログラミング言語で、企業システムやAndroid開発で広く利用されています。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["java"],
      types: ["backend", "mobile"],
    },
    {
      title: "C / C++ / C#",
      description: "低レベルシステム、高性能アプリケーション、企業向けソフトウェア開発に使用されるプログラミング言語群です。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["c_family"],
      types: ["backend"],
    },
    {
      title: "Rust",
      description: "メモリ安全性と高いパフォーマンスを重視したプログラミング言語で、重要なシステム開発に適しています。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["rust"],
      types: ["backend"],
    },
    {
      title: "Python",
      description: "自動化、データ分析、バックエンド開発、AI分野などで利用される汎用性の高いプログラミング言語です。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["python"],
      types: ["backend"],
    },
    {
      title: "SQL",
      description: "リレーショナルデータベースの検索、操作、管理を行うための標準言語です。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["sql"],
      types: ["database"],
    },
    {
      title: "MySQL",
      description: "Webアプリケーションで広く利用されているリレーショナルデータベース管理システムです。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["mysql"],
      types: ["database"],
    },
    {
      title: "MSSQL",
      description: "Microsoftが提供するリレーショナルデータベース管理システムで、企業向けシステムでよく利用されています。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["mssql"],
      types: ["database"],
    },
    {
      title: "PostgreSQL",
      description: "高い信頼性と複雑なクエリへの対応力を持つ高度なリレーショナルデータベースです。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["postgresql"],
      types: ["database"],
    },
    {
      title: "Android Studio",
      description: "Androidアプリケーションを開発するための公式統合開発環境（IDE）です。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["android_studio"],
      types: ["mobile", "tools"],
    },
    {
      title: "Kotlin",
      description: "Javaとの相互運用が可能で、簡潔さと安全性を重視したモダンなプログラミング言語です。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["kotlin"],
      types: ["mobile", "backend"],
    },
    {
      title: "Jetpack Compose",
      description: "宣言型UIを用いてAndroidインターフェースを構築するためのモダンなツールキットです。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["jetpack_compose"],
      types: ["mobile"],
    },
    {
      title: "Docker",
      description: "アプリケーションをコンテナ化し、一貫した環境で実行できるようにするプラットフォームです。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["docker"],
      types: ["devops"],
    },
    {
      title: "AWS",
      description: "アプリケーションのデプロイ、保存、スケーリングを行うためのクラウドサービスプラットフォームです。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["aws"],
      types: ["devops"],
    },
    {
      title: "Figma",
      description: "UIデザイン、プロトタイプ作成、デザインシステム管理のための共同作業ツールです。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["figma"],
      types: ["design"],
    },
    {
      title: "Git (GitHub/GitLab)",
      description: "ソースコード管理とチーム開発を支援する分散型バージョン管理システムです。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["git_github"],
      types: ["tools", "devops"],
    },
    {
      title: "BPMN",
      description: "業務プロセスを可視化し、文書化するための標準的なモデリング記法です。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["bpmn"],
      types: ["management"],
    },
    {
      title: "UML",
      description: "システムの構造や振る舞いを表現するためのモデリング言語です。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["uml"],
      types: ["management"],
    },
    {
      title: "Data Analysis with Python",
      description: "Pythonを使用したデータ分析、データ処理、およびデータ可視化の経験があります。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["pandas"],
      types: ["backend"],
    },
    {
      title: "Jest (Testing)",
      description: "JavaScript向けのテストフレームワークで、コードの品質と信頼性を確保するために使用します。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["jest"],
      types: ["frontend", "backend"],
    },
    {
      title: "Yarn",
      description: "高速で信頼性の高いJavaScriptパッケージマネージャーです。決定的なlockfileによる依存関係管理を提供します。",
      years: "5年",
      projects: "0",
      img: "",
      badges: ["yarn"],
      types: ["tools"],
    },
    {
      title: "Agile Methodologies (Scrum, Kanban, BDD)",
      description: "継続的な価値提供とチーム協力を重視したアジャイル開発手法です。Scrum、Kanban、BDDの経験があります。",
      years: "5年",
      projects: "6",
      img: "",
      badges: ["agile"],
      types: ["management"],
    }] satisfies SkillPageSkill[],
  },
}
