export const infoTextsCollection = {
  br: {
    name: "Emídio Aranha",
    role: "Desenvolvedor Full Stack | Soluções Web, Mobile & IoT",
    about: "Sobre mim",
    education: "Formação",
    experience: "Experiências",
    skills: "Habilidades",
    certifications: "Certificações",
    projects: "Projetos",
    contact: "Contato",
    downloadCV: "Baixar Currículo",
    contactMe: "Contate-me",
    techStack: "React + React Native | Android | Angular | PHP | IA",
    footerRights: "Emídio Aranha - 2026. Todos os direitos reservados.",
    professionalResume: [
        "Desenvolvedor Web Full Stack com 5 anos de Experiência no mercado de tecnologia.",
        "Graduado em Ciência da Computação pela Universidade Federal do Amazonas (UFAM). Qualificado em cursos  voltados a área de desenvolvimento Web e Android com sistemas Embarcados, além de Inglês Avançado e Japonês Intermediário.",
        "Expertise em: desenvolvimento de sistemas web, desktop e aplicativos mobile com diferentes finalidades (sejam elas para gerenciamento de informações remotas ou funcionalidades direcionadas. Ex: conexão IOT/Embarcados), planejamento de requisitos, produção de Mock-ups, UX/UI, facilitação de cerimônias ágeis (Scrum, planning, daily) mentoria e, ou acompanhamento de novos integrantes e treinamento de usuários.",
        "Motivado a melhorar a cada dia, buscando sempre novos desafios e oportunidades de aprendizado. Atualmente exploarando Inteligência Artificial com sistemas de visão e aprendizado de máquina para uso industrial.",
        <u>Principais Empresas: DELTA SOLLUTIONS, ICTS</u>,
        <u>Empresas atendidas: Daikin, INOVA, Conecthus, Elgin, Inventus Power, Flex</u>,
    ],
    globalSkills: [
        "Desenvolvimento de aplicações Web responsivas com React, React Native, Hooks e Redux",
        "Expertise em HTML, CSS, Javascript e Typescript",
        "Criação e Integração de API´s com API Rest, Graph QL, Spring boot",
        "Desenvolvimento de casos de testes para validação de features usando Jest",
        "Participação na definição de Clean Architecture e Storytelling",
        "Noções de conceito SOLID",
        "Versionamento, análise e review de código usando GIT, Github ou Gitlab",
        "Desenvolvimento de aplicações em Ambiente Linux e Windows",
        "Atuação na análise de logs, troubleshooting, manutenção e evolução do Software",
        "Desenvolvimento/ajuste de mockups com Figma focado em UX/UI",
        "Criação e evolução de Design Systems",
        "Gerenciamento de manuais e ATAS de desenvolvimento",
        "Mapeamento/Definição/Gerenciamento de Tarefas",
        "Resiliência e adaptabilidade com ferramentas novas",
        "Noções de CI | CD para Deploy de sistemas",
    ],
},
  en: {
    name: "Emídio Aranha",
    role: "Full Stack Developer | Web, Mobile & IoT Solutions",
    about: "About me",
    education: "Education",
    experience: "Experience",
    skills: "Skills",
    certifications: "Certifications",
    projects: "Projects",
    contact: "Contact",
    downloadCV: "Download Curriculum",
    contactMe: "Contact me",
    techStack: "React + React Native | Android | Angular | PHP | AI",
    footerRights: "Emídio Aranha - 2026. All rights reserved.",
    professionalResume: [],
    globalSkills: [],
  },
  ja: {
    name: "エミジオ・アラーニャ",
    role: "フルスタック開発者｜Web・モバイル・IoT",
    about: "プロフィール",
    education: "学習・経歴",
    experience: "経験",
    skills: "スキル",
    certifications: "資格・認定",
    projects: "制作実績",
    contact: "コンタクト",
    downloadCV: "CVをダウンロード",
    contactMe: "気軽に連絡してください",
    techStack: "React／React Native｜Android｜Angular｜PHP｜AI",
    footerRights: "エミジオ・アラーニャ - 2026. All rights reserved.",
    professionalResume: [],
    globalSkills: [],
  },
};

export type InfoTextsLanguage = keyof typeof infoTextsCollection;
export type InfoTexts = (typeof infoTextsCollection)[InfoTextsLanguage];