import type {
  CertificateItem,
  EducationActivity,
  EducationLeafLabels,
  EducationYearEntry,
  SkillPageSkill,
} from "./Types";

export type { EducationActivity, EducationLeafLabels, EducationYearEntry };

export const infoTextsCollection = {
  br: {
    name: "Emídio Aranha",
    role: "Desenvolvedor Full Stack | Soluções Web, Mobile & IoT",
    about: "Sobre mim",
    education: "Formação",
    experience: "Experiências",
    skills: "Habilidades",
    certifications: "Certificações",
    projects: "Projetos",
    contact: "Contatos",
    downloadCV: "Baixar Currículo",
    contactMe: "Contate-me",
    techStack: "React + React Native | Android | Angular | PHP | IA",
    footerRights: "Emídio Aranha - 2026. Todos os direitos reservados.",
    profile_page: {
      second_title: "Atribuições Gerais",
      professionalResume: [
        "Desenvolvedor Web Full Stack com 5 anos de Experiência no mercado de tecnologia.",
        "Graduado em Ciência da Computação pela Universidade Federal do Amazonas (UFAM). Qualificado em cursos  voltados a área de desenvolvimento Web e Android com sistemas Embarcados, além de Inglês Avançado e Japonês Intermediário.",
        "Expertise em: desenvolvimento de sistemas web, desktop e aplicativos mobile com diferentes finalidades (sejam elas para gerenciamento de informações remotas ou funcionalidades direcionadas. Ex: conexão IOT/Embarcados), planejamento de requisitos, produção de Mock-ups, UX/UI, facilitação de cerimônias ágeis (Scrum, planning, daily) mentoria e, ou acompanhamento de novos integrantes e treinamento de usuários.",
        "Motivado a melhorar a cada dia, buscando sempre novos desafios e oportunidades de aprendizado. Atualmente exploarando Inteligência Artificial com sistemas de visão e aprendizado de máquina para uso industrial.",
        <u>Principais Empresas: DELTA SOLLUTIONS, ICTS</u>,
        <u>Empresas atendidas: Daikin, INOVA, Conecthus, Elgin, Inventus Power, Flex</u>,
      ],
      globalSkills: [
        "Desenvolvimento de aplicações Web responsivas com React, React Native, Hooks e Redux",
        "Expertise em HTML, CSS, Javascript e Typescript",
        "Criação e Integração de API´s com API Rest, Graph QL, Spring boot",
        "Desenvolvimento de casos de testes para validação de features usando Jest",
        "Participação na definição de Clean Architecture e Storytelling",
        "Noções de conceito SOLID",
        "Versionamento, análise e review de código usando GIT, Github ou Gitlab",
        "Desenvolvimento de aplicações em Ambiente Linux e Windows",
        "Atuação na análise de logs, troubleshooting, manutenção e evolução do Software",
        "Desenvolvimento/ajuste de mockups com Figma focado em UX/UI",
        "Criação e evolução de Design Systems",
        "Gerenciamento de manuais e ATAS de desenvolvimento",
        "Mapeamento/Definição/Gerenciamento de Tarefas",
        "Resiliência e adaptabilidade com ferramentas novas",
        "Noções de CI | CD para Deploy de sistemas",
      ],
    },
    experience_page: {
      role_title: "Cargo",
      actions_title: "Atribuições",
      projects_title: "Projetos Relevantes",
      responsibility_title: "Responsabilidade",
      items: [
        {
          id: "delta",
          label: "Delta Sollutions",
          role: "Desenvolvedor Full Stack",
          time_working: "Maio 2025 - Atual",
          photos: [
            "photo1",
            "photo2",
            "delta_project_1",
            "delta_project_2",
            "delta_project_3",
            "delta_project_4",
            "delta_project_5",
            "delta_project_6",
            "delta_project_7",
            "delta_project_8",
            "delta_project_9",
            "delta_project_10",
            "delta_project_11",
            "delta_project_12",
          ],
          actions: [
            "Desenvolvimento de aplicações Web/Desktop utilizando React + Vite, React Router, Redux, Node.js, TypeScript, Material UI, Bootstrap e Styled Components",
            "Desenvolvimento de sistemas embarcados com ESP32 e Raspberry Pi (Pi OS) para aplicações industriais",
            "Implementação de soluções de Visão Computacional com Python + Open CV e integração com dispositivos industriais (Keyence)",
            "Definição e implementação de arquitetura de sistemas integrando IHM, MES e AWS",
            "Deploy e gerenciamento de aplicações com Docker, AWS e Python",
            "Integração, testes e acompanhamento de sistemas em ambiente industrial",
            "Manutenção e evolução de aplicações Desktop em C# para JIGs industriais",
            "Modelagem e manipulação de dados em MySQL, SQL Server e PostgreSQL (CRUD, queries e estruturação de tabelas)",
            "Desenvolvimento de Provas de Conceito (PoC) para validação de tecnologias e componentes; ",
            "Levantamento de requisitos e suporte à customização de soluções junto ao cliente",
            "Uso de Git (GitHub/GitLab) e ferramentas de gestão (Trello, Monday) com metodologias ágeis (Scrum/Kanban)",
            "Criação de mockups e interfaces (UX/UI) utilizando Figma",
            "Documentação técnica e treinamento de usuários finais",
            "Mentoria e onboarding de novos colaboradores, além de apoio em programas de capacitação",
          ],
          projects: [
            {
              project: "FCT (Functional Circuit Test) - Delta Bastidor JIG de Teste Personalizado",
              resume: "Sistema Automatizado para Testes de Placas Eletrônicas.",
              tasks_executed: "Encarregado de criar o software do jig desde o mockup à execução da programação frontend, backend, banco e comunicação com o firwmare em Raspberry Pi.",
            },
            {
              project: "Painel Eletrônico de Controle e Monitoramento",
              resume: "Projeto para aplicações industriais que exigem coleta de dados, monitoramento e controle preciso de processos.",
              tasks_executed: "Encarregado de criar o software do painel dashboard desde o mockup à execução da programação frontend, backend, banco e comunicação com MQTT Mosquito para transferência de dados via rede. Também responsável pela hospedagem da aplicação em AWS.",
            },
            {
              project: "Sistema de visão computacional personalizado para detecção de defeitos em componentes eletrônicos",
              resume: "Um sistema industrial composto por software e hardware voltado para julgamento de peças e componentes eletrônicos em linha de produção.",
              tasks_executed: "Responsável pela criação do software do sistema desde o mockup ao desenvolvimento do frontend, backend e comunicação via Modbus com o CLP delta que controla a automação do hardware. Também responsável pela lógica do julgamento da visão computacional mais treinamento e comunicação com o sistema de embarcados da Keyence (Câmera e softewre).",
            },
          ],
        },
        {
          id: "icts",
          label: "ICTS",
          role: "Desenvolvedor Web/Mobile Full Stack",
          time_working: "Setembro 2020 – Fevereiro 2024  ",
          photos: [],
          actions: [
            "Desenvolvimento de aplicações Web/Desktop utilizando React + Yarn, Redux, Node.js, PHP, TypeScript, Material UI, Bootstrap e Styled Components",
            "Desenvolvimento de aplicações Mobile para integração com os sistemas web em React Native e Android Studio",
            "Modelagem e manipulação de dados em MySQL, SQL Server e PostgreSQL (CRUD, queries e estruturação de tabelas)",
            "Produção de Provas de Conceito (PoC) para implementação de novas funcionalidades como ex: GraphQL para consulta em bancos e Spring Boot para facilitar criação de APIs",
            "Levantamento de requisitos e suporte à customização de soluções junto ao cliente",
            "Otimização da visualização e análise de dados com Python Pandas",
            "Manutenção e refatoração de sistemas legados",
            "Apoio na adaptação de novas tecnologias e boas práticas de desenvolvimento utilizando Trello como gerenciador e GitHub/GitLab para controle de versionamento e revisão de códigos", 
            "Atuação como mentor de novos colaboradores, auxiliando no onboarding técnico",
            "Participação em planejamentos com método Scrum + planning e Kanban",
            "Desenvolvimento e aplicação de melhorias em mockups",
          ],
          projects: [
            {
              project: "Sistema de Gerenciamento Empresarial Com Dashboard",
              resume: "Participação no desenvolvimento de um sistema de gerenciamento empresarial responsável por catalogar a entradas e saída de colaboradores, terceiros, visitas, veículos e materiais na portaria, na produção e refeitório. Além do espaço de monitoramento das linhas para identificação de somente pessoas autorizadas na produção, página de controle de produção diária e sistema mobile de suporte para registro de veículos e materiais.",
              tasks_executed: "Desenvolver o frontend Web e Mobile do sistema, Apis, e uma aplicação mobile auxiliar para registro de veículos e materiais.",
            },
            {
              project: "Sistema de Gerenciamento para Letreiros LED de Placas e Veículos",
              resume: "Participação no desenvolvimento de um sistema de cadastro e gerenciamento de mensagens para letreiros LED de placas para avisos e veículos sinalizadores (letreiros de ônibus por exemplo).",
              tasks_executed: "Responsável pela manutenção e evolução com acrescimo de novas funcionalidades e refatoração de código legado Frontend e Backend.",
            },
          ],
        },
        {
          id: "freelance",
          label: "Freelancer",
          role: "Desenvolvedor Freelancer",
          time_working: "Fevereiro 2024 - Abril 2025",
          photos: [],
          actions: [
            "Desenvolvimento de soluções sob demanda para clientes diversos.",
            "Criação de interfaces responsivas e integrações com APIs.",
            "Suporte pós-entrega e evolução de funcionalidades.",
            "Desenvolvimento de aplicações em Java, PHP com Laravel e Angular."
          ],
          projects: [
            {
              project: "Air Quality App",
              resume: "Projeto do DevTitans. Sistema embarcado com Android microcontrolador ESP32 e sensores para detecção de poluentes e gases no ar",
              tasks_executed: "Desenvolvimento da aplicação com Android Studio, Kotlin e Composer, desenvolvimento do mockup UX UI do sistema, integração com API do google Maps e salvamento dos dados no Firebase, conexão com a placa Esp32 e componentes de captação de qualidade do ar. Responsável pera direção e apresentação do projeto",
            },
            {
              project: "Icomp Números",
              resume: "Projeto de conclusão de curso. Software, em Node com Handlebars, de coleta de dados via upload de arquivos XML para gerenciamento de informações técnicas dos corpo docentes do ICOMP/UFAM. ",
              tasks_executed: "Desenvolvimento do Frontend e Backend do sistema e o tratamento de dados XML para parseamento dos campos na interface werb.",
            },
            {
              project: "MindTrack Agenda",
              resume: "Aplicação de gerenciamento de atividades psicológicas/psiquiátricas para acompanhamento pessoal e profissional aplicando LLM",
              tasks_executed: "Desenvolvimento do Frontend e Backend em Android Studio com Kotlin + composer e conexão com Llama para geração de respostas",
            },
            {
              project: "Sistema de Gerenciamento de PetShop",
              resume: "Sistema desktop em Java proposto para gerenciamento de atividades de um PetShop com consultas veterinárias, banho & tosa, e gerenciamento de materiais de venda.",
              tasks_executed: "Desenvolvimento do Frontend e Backend em Java com Swing para interface gráfica e conexão com banco de dados MySQL.",
            },
            // {
            //   project: "1",
            //   resume: "1",
            //   tasks_executed: "1",
            // }
          ],
        },
      ],
    },
    education_page: {
      leafLabels: {
        institution: "Instituição:",
        degree: "Grau:",
        period: "Período:",
        location: "Cidade | Estado:",
        description: "Descrição:",
        scholar: "Bolsista:",
        extra: "Extras:",
      },
      education: [
        {
          year: 2012,
          activities: [
            {
              title: "Curso de Lingua Inglesa Jovens Iniciantes",
              institution: "Minds",
              degree: "Curso de capacitção",
              period: "Janeiro 2010 - julho 2012",
              location: "Manaus - AM",
              ended: "Jul",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2014,
          activities: [
            {
              title: "Curso de Lingua Inglesa nível básico ao avançado",
              institution: "SENAC",
              degree: "Curso de capacitção",
              period: "Agosto 2012 - Dezembro 2014",
              location: "Manaus - AM",
              ended: "Dez",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2015,
          activities: [
            {
              title: "Ensino Escolar Completo",
              institution: "Escola Celus",
              degree: "Ensino Fundamental e Médio",
              period: "Janeiro 2000 - Dezembro 2015",
              location: "Manaus - AM",
              ended: "Dez",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2020,
          activities: [
            {
              title: "Ensino em Lingua Japonesa nível básico ao avançado",
              institution: "NIPPAKU",
              degree: "Curso de capacitação",
              period: "Janeiro 2015 - Setembro 2020",
              location: "Manaus - AM",
              ended: "Set",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2022,
          activities: [
            {
              title: "Graduação em Ciência da Computação",
              institution: "Universidade Federal do Amazonas (UFAM)",
              degree: "Ensino Superior Completo",
              period: "Abril 2016 - Julho 2022",
              location: "Manaus - AM",
              ended: "Jul",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2025,
          activities: [
            {
              title: "DevTitans",
              institution: "Universidade Federal do Amazonas (UFAM)",
              degree: "Curso de Capacitação",
              period: "Agosto 2024 - Fevereiro 2025",
              location: "Manaus - AM",
              ended: "Fev",
              description: "Capacitação e Desenvolvimento em tecnologias Android para Sistemas Embarcados",
              scholar: "Fundação de Apoio ao Ensino, Pesquisa, Extensão e Interiorização do IFAM, FAEPI, Brasil.",
              extra: "",
            },
          ],
        },
      ],
    },
    skill_page: {
      skills: [
        {
          title: "React",
          description: "Biblioteca para construção de interfaces dinâmicas baseada em componentes, utilizando tanto classes quanto Hooks para gerenciamento de estado e ciclo de vida.",
          years: "5 ano",
          projects: "11",
          img: "",
          badges: ["react"],
          types: ["frontend"],
        },
        {
          title: "React Native + Expo",
          description: "Framework para desenvolvimento de aplicativos móveis nativos utilizando JavaScript/TypeScript e a mesma lógica baseada em componentes do React.",
          years: "5 ano",
          projects: "3",
          img: "",
          badges: ["react_native"],
          types: ["frontend"],
        },
        {
          title: "JavaScript + TypeScript",
          description: "Linguagens utilizadas que atuam na construção de interfaces interativas no frontend e também na lógica de negócio no backend.",
          years: "5 ano",
          projects: "12",
          img: "",
          badges: ["typescript", "javascript"],
          types: ["frontend", "backend"],
        },
        {
          title: "Redux",
          description: "Biblioteca de gerenciamento de estado global que centraliza e organiza os dados da aplicação de forma previsível. Modelos trabalhados: Thunk, Saga, RTK Query.",
          years: "5 ano",
          projects: "6",
          img: "",
          badges: ["redux"],
          types: ["frontend"],
        },
        {
          title: "HTML",
          description: "Linguagem de marcação utilizada para estruturar o conteúdo e os elementos de páginas web.",
          years: "5 ano",
          projects: "6",
          img: "",
          badges: ["html"],
          types: ["frontend"],
        },
        {
          title: "CSS",
          description: "Linguagem de estilos responsável pela aparência, layout e responsividade das interfaces web.",
          years: "5 ano",
          projects: "6",
          img: "",
          badges: ["css"],
          types: ["frontend"],
        },
        {
          title: "Material UI",
          description: "Biblioteca de componentes React que implementa o design system Material Design para criação rápida de interfaces modernas e consistentes.",
          years: "5 ano",
          projects: "3",
          img: "",
          badges: ["material_ui"],
          types: ["frontend"],
        },
        {
          title: "Bootstrap",
          description: "Framework CSS que facilita a criação de interfaces web responsivas e consistentes, com uma ampla gama de componentes pré-construídos.",
          years: "5 ano",
          projects: "6",
          img: "",
          badges: ["bootstrap"],
          types: ["frontend"],
        },
        {
          title: "Handlebars",
          description: "Template engine para geração dinâmica de HTML no backend a partir de dados estruturados.",
          years: "1",
          projects: "1",
          img: "",
          badges: ["handlebars"],
          types: ["frontend", "backend"],
        },
        {
          title: "Style Dictionary",
          description: "Ferramenta para gerenciamento e padronização de design tokens entre diferentes plataformas.",
          years: "2",
          projects: "3",
          img: "",
          badges: ["style_dictionary"],
          types: ["frontend"],
        },
        {
          title: "Unstyled Components",
          description: "Abordagem de componentes desacoplados de estilo, permitindo total controle visual via CSS ou outras bibliotecas.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["styled_components"],
          types: ["frontend"],
        },
        {
          title: "Node.js",
          description: "Ambiente de execução JavaScript no servidor utilizado para construção de aplicações backend escaláveis.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["node"],
          types: ["backend"],
        },
        {
          title: "Express",
          description: "Framework minimalista para Node.js utilizado na criação de APIs e aplicações web.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["express"],
          types: ["backend"],
        },
        {
          title: "Sequelize",
          description: "ORM para Node.js que facilita a comunicação e manipulação de bancos de dados relacionais.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["sequelize"],
          types: ["backend", "database"],
        },
        {
          title: "API REST",
          description: "Arquitetura para desenvolvimento de APIs baseada em requisições HTTP e comunicação padronizada entre sistemas.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["rest_api"],
          types: ["backend"],
        },
        {
          title: "GraphQL",
          description: "Linguagem de consulta para APIs que permite solicitar exatamente os dados necessários de forma eficiente.",
          years: "1",
          projects: "1",
          img: "",
          badges: ["graphql"],
          types: ["backend"],
        },
        {
          title: "Spring Boot",
          description: "Framework Java para criação rápida de aplicações backend robustas e escaláveis.",
          years: "1",
          projects: "1",
          img: "",
          badges: ["spring_boot"],
          types: ["backend"],
        },
        {
          title: "Docker",
          description: "Plataforma de containerização que permite empacotar e executar aplicações de forma isolada e consistente.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["docker"],
          types: ["devops"],
        },
        {
          title: "AWS",
          description: "Plataforma de serviços em nuvem utilizada para deploy, armazenamento e escalabilidade de aplicações.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["aws"],
          types: ["devops"],
        },
        {
          title: "Figma",
          description: "Ferramenta de design colaborativo para criação de interfaces, protótipos e sistemas de design.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["figma"],
          types: ["design"],
        },
        {
          title: "SQL",
          description: "Linguagem padrão para consulta, manipulação e gerenciamento de bancos de dados relacionais.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["sql"],
          types: ["database"],
        },
        {
          title: "MySQL",
          description: "Sistema de gerenciamento de banco de dados relacional amplamente utilizado em aplicações web.",
          years: "5",
          projects: "6",
          img: "",  
          badges: ["mysql"],
          types: ["database"],
        },
        {
          title: "MSSQL",
          description: "Sistema de banco de dados relacional da Microsoft utilizado em aplicações corporativas.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["mssql"],
          types: ["database"],
        },
        {
          title: "PostgreSQL",
          description: "Banco de dados relacional avançado, conhecido por sua robustez e suporte a consultas complexas.",
          years: "5",
          projects: "6  ",
          img: "",
          badges: ["postgresql"],
          types: ["database"],
        },
        {
          title: "Android Studio",
          description: "Ambiente de desenvolvimento oficial para criação de aplicações Android.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["android_studio"],
          types: ["mobile"],
        },
        {
          title: "Kotlin",
          description: "Linguagem moderna utilizada no desenvolvimento Android, interoperável com Java e focada em concisão e segurança.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["kotlin"],
          types: ["mobile"],
        },
        {
          title: "Jetpack Compose",
          description: "Toolkit moderno para construção de interfaces Android de forma declarativa.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["jetpack_compose"],
          types: ["mobile"],
        },
        {
          title: "Java",
          description: "Linguagem de programação orientada a objetos amplamente utilizada em sistemas corporativos e Android.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["java"],
          types: ["backend"],
        },
        {
          title: "C / C++ / C#",
          description: "Conjunto de linguagens utilizadas para desenvolvimento de sistemas de baixo nível, aplicações performáticas e software corporativo.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["c_family"],
          types: ["backend"],
        },
        {
          title: "Rust",
          description: "Linguagem focada em segurança de memória e alta performance para sistemas críticos.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["rust"],
          types: ["backend"],
        },
        {
          title: "Python",
          description: "Linguagem versátil utilizada em automação, análise de dados, backend e inteligência artificial.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["python"],
          types: ["backend"],
        },
        {
          title: "Git (GitHub/GitLab)",
          description: "Sistema de controle de versão distribuído para gerenciamento de código e colaboração em equipe.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["git_github"],
          types: ["devops"],
        },
        {
          title: "BPMN",
          description: "Notação gráfica para modelagem e documentação de processos de negócio.",
          years: "5",
          projects: "6 ",
          img: "",
          badges: ["bpmn"],
          types: ["backend"],
        },
        {
          title: "UML",
          description: "Linguagem de modelagem utilizada para representar a estrutura e o comportamento de sistemas.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["uml"],
          types: ["backend"],
        },
        {
          title: "Storybook",
          description: "Ferramenta para desenvolvimento e documentação isolada de componentes de interface.",
          years: "5",
          projects: "6",
          img: "",
          badges: ["storybook"],
          types: ["frontend"],
        },
        {
          title: "Data Analysis with Python",
          description: "Uso de Python para análise, processamento e visualização de dados.",
          years: "5",   
          projects: "6",
          img: "",    
          badges: ["pandas"],
          types: ["backend"],
        },
        {
          title: "Jest (Testing)",
          description: "Framework de testes para JavaScript utilizado para garantir qualidade e confiabilidade do código.",
          years: "5",
          projects: "6",
          img: "",  
          badges: ["jest"],
          types: ["frontend", "backend"],
        },
        {
          title: "Agile Methodologies (Scrum, Kanban, BDD)",
          description: "Metodologias ágeis para gerenciamento de projetos com foco em entrega contínua e colaboração.",
          years: "5",
          projects: "6 ",
          img: "",
          badges: ["agile"],
          types: ["management"],
        },
      ] satisfies SkillPageSkill[],
    },
    certificate_page: {
      certificates: [
        {
          id: "c1",
          title: "Bacharel em Ciência da Computação",
          institution: "UFAM (Universidade Federal do Amazonas)",
          resume:
            "O reitor da Universidade Federal do Amazonas (UFAM), no uso de suas atribuições e tendo em vista a conclusão do curso de Ciência da Computação em 28 de Junho de 2022, confere o título de Bacharel em Ciência da Computação ao(a) Emídio José Aranha Cardoso Filho, brasileiro, natural do estado do Amazonas, nascido em 13 de Novembro de 1997, e outorga-lhe o presente DIPLOMA, a fim de que possa gozar de todos os direitos e prerrogativas legais. Manaus 14 de Julho de 2022.",
          img: "c1",
        },
        {
          id: "c2",
          title: "Certificado de Extensão DevTitans",
          institution: "UFAM (Universidade Federal do Amazonas)",
          resume:
            'Certificado que Emídio José Aranha Cardoso Filho participou da 6º turma do projeto "DevTITANS - Capacitação e Desenvolvimento em Tecnologias Android para Sistemas Embarcados", coordenado por Horácio Antônio Braga Fernandes de Oliveira, realizado no período de 22 de Agosto de 2024 a 27 de Fevereiro de 2025, promovido pela Pró-Reitoria de Extensão da UFAM. Com carga horária de 240 horas.',
          img: "c2",
        },
        {
          id: "c3",
          title: "Javascript & Typescript do Básico ao Avançado",
          institution: "Udemy",
          resume:
            "Curso completo de JavaScript e TypeScript do básico ao avançado com foco em desenvolvimento full stack utilizando tecnologias modernas de front-end e back-end. O conteúdo aborda JavaScript puro (Vanilla JS), Node.js, Express, MongoDB, MySQL, MariaDB, React, Redux, React Hooks, Webpack, Babel e TypeScript. O aluno aprende a criar projetos reais com CRUD, autenticação, APIs REST e sistemas de login usando Sessions e JWT. O curso também ensina deploy em Linux com NGINX, PM2, SSL/TLS, Git e SSH, além de práticas de segurança para aplicações. Inclui módulos sobre Programação Orientada a Objetos, princípios SOLID, testes automatizados com Jest, Expressões Regulares e Design Patterns. Na parte de React, são desenvolvidas aplicações integradas ao back-end utilizando Redux Saga e autenticação JWT. Também há conteúdo sobre Next.js, Strapi, SSR, SSG, ISR, bancos de dados SQL e Query Builder com Knex. O curso ainda oferece bônus de HTML5 e CSS3 e é indicado tanto para iniciantes quanto para desenvolvedores que desejam aprimorar conhecimentos e atuar como full stack.",
          img: "c3",
        },
        {
          id: "c4",
          title: "React + Redux, Material UI, Hooks, Typescript e API's Rest",
          institution: "Udemy",
          resume:
            "Curso voltado ao desenvolvimento de aplicações web modernas utilizando React e tecnologias atuais do ecossistema front-end. O conteúdo aborda JavaScript, EcmaScript, TypeScript, HTML, CSS, Bootstrap e Material UI para criação de interfaces modernas e responsivas. O aluno aprende os fundamentos do React, incluindo componentes, estados, propriedades, componentes de classe, componentes funcionais e React Hooks. Também são ensinadas integrações com APIs REST utilizando bibliotecas HTTP e gerenciamento de estado com Redux. O curso foca na criação de aplicações completas do zero utilizando boas práticas de programação e organização de projetos. Inclui exemplos práticos com React Hooks e TypeScript, além de conceitos essenciais para aplicações web ricas e dinâmicas. É indicado para desenvolvedores que desejam aprender React, se atualizar no mercado e aprofundar conhecimentos em desenvolvimento front-end moderno.",
          img: "c4",
        },
        {
          id: "c5",
          title: "Curso React + Redux: Fundamentos e 2 Apps do Absoluto ZERO!",
          institution: "Udemy",
          resume:
            "Curso prático de desenvolvimento web com React e JavaScript moderno focado na construção de aplicações completas do zero. O conteúdo aborda fundamentos de React, Redux e Webpack antes da criação de projetos reais, permitindo que iniciantes compreendam o ecossistema envolvido no desenvolvimento front-end e full stack. Também inclui tecnologias back-end como Node.js, Express e MongoDB, além de tópicos avançados como formulários dinâmicos e middlewares. O aluno aprende a configurar aplicações com Webpack, criar componentes reutilizáveis em React, integrar Redux para gerenciamento de estado e aplicar boas práticas de desenvolvimento. O curso ainda possui uma seção dedicada ao Next.js, abordando SSR, renderização estática, roteamento e desenvolvimento de um CRUD completo utilizando Firebase, Firestore, TailwindCSS e TypeScript. É indicado para programadores que desejam aprender React, Redux e desenvolvimento profissional de aplicações web completas.",
          img: "c5",
        },
        {
          id: "c6",
          title: "Entendendo e documentando REST / RESTful APIs",
          institution: "Udemy",
          resume:
            "Curso focado nos conceitos e fundamentos de APIs RESTful, com o objetivo de ensinar como projetar, compreender e documentar APIs modernas em qualquer linguagem de programação. O conteúdo aborda arquitetura REST, modelo de maturidade RESTful, boas práticas no desenvolvimento de APIs, utilização do cURL para testes de requisições, Media Types, versionamento de APIs e técnicas de cache para aplicações web. Também são ensinados métodos de autenticação utilizando OAuth e JWT para segurança de APIs REST. Além disso, o curso possui uma seção dedicada à documentação de APIs utilizando Swagger, facilitando integração, manutenção e consumo de serviços. É indicado para desenvolvedores front-end, back-end, desenvolvedores web e engenheiros de software que desejam aprofundar conhecimentos em desenvolvimento e arquitetura de APIs RESTful.",
          img: "c6",
        },
        {
          id: "c7",
          title: "Desenvolvimento Web com PHP e Banco de Dados MySQL",
          institution: "Udemy",
          resume:
            "Curso de desenvolvimento web utilizando PHP e MySQL voltado para criação de websites dinâmicos e integrados a bancos de dados. O conteúdo aborda fundamentos da linguagem PHP para programação back-end, conceitos essenciais de SQL e utilização do MySQL como sistema de gerenciamento de banco de dados. O aluno aprende a criar sistemas web com autenticação e login, desenvolver aplicações conectadas ao banco de dados, construir e gerenciar bases de dados e implementar senhas criptografadas para maior segurança. Também são apresentadas técnicas de proteção contra SQL Injection e boas práticas no desenvolvimento de aplicações web. O curso é indicado para programadores web, profissionais da computação e pessoas interessadas em aprender programação para internet utilizando PHP e MySQL.",
          img: "c7",
        },
      ] satisfies CertificateItem[],
    },
    contactme_page: {
      title: "Vamos conversar?",
      description:
        "Entre em contato comigo para discutir oportunidades de colaboração, projetos ou simplesmente para trocar ideias. Estou sempre aberto a novas conexões e oportunidades de aprendizado.",
      phone_label: "Telefone",
      phone: "+55 (92) 98415-8067",
      phone_href: "+5592984158067",
      phone_link: "+55 (92) 98415-8067",
      myEmail_label: "E-mail",
      myEmail: "emidioaranhadeveloper@gmail.com",
      myEmail_link: "emidioaranhadeveloper@gmail.com",
      linkedin_label: "LinkedIn",
      linkedin_url: "https://www.linkedin.com/in/emidio-aranha/",
      linkedin_link: "emidio-aranha",
      github_label: "GitHub",
      github: "https://github.com/EmidioAranha13",
      github_link: "EmidioAranha13",
      location_label: "Localização",
      location: "Manaus, AM — Brasil",
      name_label: "Nome",
      name_placeholder: "Seu nome",
      email_label: "E-mail",
      email_placeholder: "seu@email.com",
      yourContact: "Seu telefone",
      yourContact_placeholder: "Seu número de telefone",
      form_phone_invalid_message: "Preencha um telefone válido.",
      subject_label: "Assunto",
      subject_placeholder: "Assunto da mensagem",
      message_label: "Mensagem",
      message_placeholder: "Escreva sua mensagem…",
      form_submit_label: "Enviar mensagem",
      form_submitting_label: "Enviando…",
      form_success_message: "Em breve entrarei em contato.",
      form_error_message: "Não foi possível enviar. Tente novamente em instantes.",
      form_modal_success_title: "Mensagem enviada com sucesso!",
      form_modal_error_title: "Falha no envio",
      form_modal_processing_title: "Processando",
      form_modal_processing_message: "Processando mensagem",
      form_modal_close_label: "OK",
      form_debug_success_label: "Debug OK",
      form_debug_error_label: "Debug erro",
      form_config_missing_message:
        "Formulário ainda não configurado. Defina VITE_FORMSPREE_FORM_ID no arquivo .env.local.",
    },
  },
  en: {
    name: "Emídio Aranha",
    role: "Full Stack Developer | Web, Mobile & IoT Solutions",
    about: "About me",
    education: "Education",
    experience: "Experience",
    skills: "Skills",
    certifications: "Certifications",
    projects: "Projects",
    contact: "Contact",
    downloadCV: "Download Curriculum",
    contactMe: "Contact me",
    techStack: "React + React Native | Android | Angular | PHP | AI",
    footerRights: "Emídio Aranha - 2026. All rights reserved.",
    profile_page: {
      second_title: "General Responsibilities",
      professionalResume: [
        "Full Stack Web Developer with 5 years of experience in the technology market.",
        "Bachelor's degree in Computer Science from the Federal University of Amazonas (UFAM). Qualified through courses focused on Web and Android development with Embedded Systems, as well as Advanced English and Intermediate Japanese.",
        "Expertise in: development of web systems, desktop applications, and mobile apps for various purposes (such as remote information management or specific functionalities, e.g., IoT/Embedded systems integration), requirements planning, mock-up design, UX/UI, facilitation of agile ceremonies (Scrum, planning, daily), mentoring and onboarding of new team members, and user training.",
        "Motivated to continuously improve, always seeking new challenges and learning opportunities. Currently exploring Artificial Intelligence with computer vision and machine learning systems for industrial applications.",
        <u>Main Companies: DELTA SOLUTIONS, ICTS</u>,
        <u>Clients: Daikin, INOVA, Conecthus, Elgin, Inventus Power, Flex</u>,
      ],
      globalSkills: [
        "Development of responsive web applications using React, React Native, Hooks, and Redux",
        "Expertise in HTML, CSS, JavaScript, and TypeScript",
        "API creation and integration using REST APIs, GraphQL, and Spring Boot",
        "Development of test cases for feature validation using Jest",
        "Participation in defining Clean Architecture and Storytelling",
        "Understanding of SOLID principles",
        "Version control, code analysis, and review using Git, GitHub, or GitLab",
        "Application development in Linux and Windows environments",
        "Experience in log analysis, troubleshooting, maintenance, and software evolution",
        "Mockup design and adjustments using Figma with a focus on UX/UI",
        "Creation and evolution of Design Systems",
        "Management of documentation and development records",
        "Task mapping, definition, and management",
        "Resilience and adaptability to new tools",
        "Basic knowledge of CI/CD for system deployment",
      ],
    },
    experience_page: {
      role_title: "Role",
      actions_title: "Responsibilities",
      projects_title: "Relevant Projects",
      responsibility_title: "Responsabilities",
      items: [
        {
          id: "delta",
          label: "Delta Solutions",
          role: "Full Stack Developer",
          time_working: "May 2025 - Present",
          photos: [
            "photo1",
            "photo2",
            "delta_project_1",
            "delta_project_2",
            "delta_project_3",
            "delta_project_4",
            "delta_project_5",
            "delta_project_6",
            "delta_project_7",
            "delta_project_8",
            "delta_project_9",
            "delta_project_10",
            "delta_project_11",
            "delta_project_12",
          ],
          actions: [
            "Development of Web/Desktop applications using React + Vite, React Router, Redux, Node.js, TypeScript, Material UI, Bootstrap and Styled Components",
            "Development of embedded systems with ESP32 and Raspberry Pi (Pi OS) for industrial applications",
            "Implementation of Computer Vision solutions using Python + OpenCV and integration with industrial devices (Keyence)",
            "Definition and implementation of system architectures integrating HMI, MES and AWS",
            "Deployment and management of applications using Docker, AWS and Python",
            "Integration, testing and monitoring of systems in industrial environments",
            "Maintenance and evolution of Desktop applications in C# for industrial JIGs",
            "Data modeling and manipulation in MySQL, SQL Server and PostgreSQL (CRUD, queries and table structuring)",
            "Development of Proofs of Concept (PoC) for validation of technologies and components",
            "Requirements gathering and support for solution customization with clients",
            "Use of Git (GitHub/GitLab) and management tools (Trello, Monday) with agile methodologies (Scrum/Kanban)",
            "Creation of mockups and interfaces (UX/UI) using Figma",
            "Technical documentation and end-user training",
            "Mentoring and onboarding of new team members, as well as support in training programs",
          ],
          projects: [
            {
              project: "FCT (Functional Circuit Test) - Custom Test JIG Rack",
              resume: "Automated system for electronic board testing.",
              tasks_executed: "Responsible for developing the jig software from mockup to full implementation, including frontend, backend, database, and communication with firmware on Raspberry Pi.",
            },
            {
              project: "Electronic Control and Monitoring Panel",
              resume: "Industrial project focused on data collection, monitoring, and precise process control.",
              tasks_executed: "Responsible for developing the dashboard software from mockup to full implementation, including frontend, backend, database, and MQTT (Mosquitto) communication for data transfer. Also responsible for AWS deployment.",
            },
            {
              project: "Custom Computer Vision System for Defect Detection in Electronic Components",
              resume: "Industrial system combining software and hardware for inspection of electronic components in production lines.",
              tasks_executed: "Responsible for system development from mockup to frontend, backend, and Modbus communication with Delta PLC. Also handled vision logic, training, and integration with Keyence embedded system (camera and software).",
            },
          ],
        },
        {
          id: "icts",
          label: "ICTS",
          role: "Full Stack Web/Mobile Developer",
          time_working: "September 2020 – February 2024",
          photos: [],
          actions: [
            "Development of Web/Desktop applications using React + Yarn, Redux, Node.js, PHP, TypeScript, Material UI, Bootstrap and Styled Components",
            "Development of Mobile applications using React Native and Android Studio",
            "Data modeling and manipulation in MySQL, SQL Server and PostgreSQL (CRUD, queries and table structuring)",
            "Development of Proofs of Concept (PoC) for new technologies such as GraphQL and Spring Boot",
            "Requirements gathering and support for client customization",
            "Data analysis optimization using Python Pandas",
            "Maintenance and refactoring of legacy systems",
            "Support in adopting new technologies and best practices using Trello and GitHub/GitLab",
            "Mentoring new team members and technical onboarding",
            "Participation in planning using Scrum and Kanban",
            "Development and improvement of mockups",
          ],
          projects: [
            {
              project: "Enterprise Management System with Dashboard",
              resume: "Participation in the development of a system for managing employees, visitors, vehicles, and materials across different company areas, including production monitoring and mobile support.",
              tasks_executed: "Development of Web and Mobile frontend, APIs, and auxiliary mobile application.",
            },
            {
              project: "LED Display Management System",
              resume: "System for managing messages displayed on LED panels and vehicle signage.",
              tasks_executed: "Responsible for maintenance, feature implementation, and refactoring of frontend and backend systems.",
            },
          ],
        },
        {
          id: "freelance",
          label: "Freelancer",
          role: "Freelance Developer",
          time_working: "February 2024 - April 2025",
          photos: [],
          actions: [
            "Development of custom solutions for various clients",
            "Creation of responsive interfaces and API integrations",
            "Post-delivery support and feature evolution",
            "Development of applications using Java, PHP (Laravel), and Angular"
          ],
          projects: [
            {
              project: "Air Quality App",
              resume: "Embedded system project with ESP32 and sensors for air quality monitoring",
              tasks_executed: "Development using Android Studio, Kotlin and Composer, UX/UI design, Google Maps API integration, Firebase data storage, and ESP32 integration. Responsible for project leadership and presentation.",
            },
            {
              project: "Icomp Numbers",
              resume: "Final project: system for XML data processing and management of academic information",
              tasks_executed: "Frontend and backend development, XML parsing and data processing.",
            },
            {
              project: "MindTrack Agenda",
              resume: "Application for psychological/psychiatric activity management using LLM",
              tasks_executed: "Frontend and backend development using Kotlin and integration with Llama model.",
            },
            {
              project: "PetShop Management System",
              resume: "Desktop system for managing veterinary services and products",
              tasks_executed: "Development using Java Swing and MySQL database integration.",
            },
          ],
        },
      ],
    },
    education_page: {
      leafLabels: {
        institution: "Institution:",
        degree: "Degree:",
        period: "Period:",
        location: "City | State:",
        description: "Description:",
        scholar: "Scholarship:",
        extra: "Additional Information:",
      },
      education: [
        {
          year: 2012,
          activities: [
            {
              title: "English Language Course for Young Beginners",
              institution: "Minds",
              degree: "Professional Training Course",
              period: "January 2010 - July 2012",
              location: "Manaus - AM",
              ended: "Jul",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2014,
          activities: [
            {
              title: "English Language Course (Basic to Advanced)",
              institution: "SENAC",
              degree: "Professional Training Course",
              period: "August 2012 - December 2014",
              location: "Manaus - AM",
              ended: "Dec",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2015,
          activities: [
            {
              title: "Complete School Education",
              institution: "Celus School",
              degree: "Elementary and High School Education",
              period: "January 2000 - December 2015",
              location: "Manaus - AM",
              ended: "Dec",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2020,
          activities: [
            {
              title: "Japanese Language Course (Basic to Advanced)",
              institution: "NIPPAKU",
              degree: "Professional Training Course",
              period: "January 2015 - September 2020",
              location: "Manaus - AM",
              ended: "Sep",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2022,
          activities: [
            {
              title: "Bachelor's Degree in Computer Science",
              institution: "Federal University of Amazonas (UFAM)",
              degree: "Higher Education Degree",
              period: "April 2016 - July 2022",
              location: "Manaus - AM",
              ended: "Jul",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2025,
          activities: [
            {
              title: "DevTitans Program",
              institution: "Federal University of Amazonas (UFAM)",
              degree: "Professional Training Program",
              period: "August 2024 - February 2025",
              location: "Manaus - AM",
              ended: "Feb",
              description: "Training and development in Android technologies for Embedded Systems",
              scholar: "Scholarship funded by the Foundation for Support of Education, Research, Extension and Interiorization of IFAM (FAEPI), Brazil",
              extra: "",
            },
          ],
        },
      ],
    },
    skill_page: {
      skills: [
        {
          title: "React",
          description: "Component-based library for building scalable and highly interactive user interfaces, leveraging both class-based architecture and modern Hooks for state and lifecycle management.",
          years: "5 years",
          projects: "11",
          img: "",
          badges: ["react"],
          types: ["frontend"],
        },
        {
          title: "React Native + Expo",
          description: "Framework for developing cross-platform native mobile applications using JavaScript/TypeScript with React’s declarative component architecture.",
          years: "5 years",
          projects: "3",
          img: "",
          badges: ["react_native"],
          types: ["frontend"],
        },
        {
          title: "JavaScript + TypeScript",
          description: "Core languages used to build dynamic frontend experiences and scalable backend business logic with strong typing and modern ECMAScript standards.",
          years: "5 years",
          projects: "12",
          img: "",
          badges: ["typescript", "javascript"],
          types: ["frontend", "backend"],
        },
        {
          title: "Redux",
          description: "Predictable global state management library designed to centralize and orchestrate application data efficiently. Experienced with Thunk, Saga, and RTK Query patterns.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["redux"],
          types: ["frontend"],
        },
        {
          title: "HTML",
          description: "Standard markup language used to structure semantic content and define the foundation of modern web applications.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["html"],
          types: ["frontend"],
        },
        {
          title: "CSS",
          description: "Styling language responsible for visual presentation, responsive layouts, animations, and user interface consistency across platforms.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["css"],
          types: ["frontend"],
        },
        {
          title: "Material UI",
          description: "React component library implementing Google’s Material Design system for rapidly building polished and accessible interfaces.",
          years: "5 years",
          projects: "3",
          img: "",
          badges: ["material_ui"],
          types: ["frontend"],
        },
        {
          title: "Bootstrap",
          description: "Responsive CSS framework offering reusable UI components and layout utilities for fast and consistent web development.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["bootstrap"],
          types: ["frontend"],
        },
        {
          title: "Handlebars",
          description: "Template engine used for dynamic HTML generation on the backend through structured and reusable data rendering.",
          years: "1 year",
          projects: "1",
          img: "",
          badges: ["handlebars"],
          types: ["frontend", "backend"],
        },
        {
          title: "Style Dictionary",
          description: "Tool designed for managing and synchronizing design tokens consistently across multiple platforms and design systems.",
          years: "2 years",
          projects: "3",
          img: "",
          badges: ["style_dictionary"],
          types: ["frontend"],
        },
        {
          title: "Unstyled Components",
          description: "Approach focused on decoupling logic from styling, enabling complete visual customization through CSS or alternative styling solutions.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["styled_components"],
          types: ["frontend"],
        },
        {
          title: "Node.js",
          description: "Server-side JavaScript runtime environment used to build scalable, event-driven, and high-performance backend applications.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["node"],
          types: ["backend"],
        },
        {
          title: "Express",
          description: "Minimalist Node.js framework widely adopted for building RESTful APIs and robust web server architectures.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["express"],
          types: ["backend"],
        },
        {
          title: "Sequelize",
          description: "ORM for Node.js that simplifies relational database modeling, querying, and data manipulation through abstraction layers.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["sequelize"],
          types: ["backend", "database"],
        },
        {
          title: "API REST",
          description: "Architectural style for designing scalable APIs using standardized HTTP communication principles between distributed systems.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["rest_api"],
          types: ["backend"],
        },
        {
          title: "GraphQL",
          description: "Query language for APIs enabling clients to retrieve precisely the required data with optimized and flexible requests.",
          years: "1 year",
          projects: "1",
          img: "",
          badges: ["graphql"],
          types: ["backend"],
        },
        {
          title: "Spring Boot",
          description: "Java-based framework for rapidly building enterprise-grade backend services and scalable microservice architectures.",
          years: "1 year",
          projects: "1",
          img: "",
          badges: ["spring_boot"],
          types: ["backend"],
        },
        {
          title: "Docker",
          description: "Containerization platform used to package, isolate, and deploy applications consistently across different environments.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["docker"],
          types: ["devops"],
        },
        {
          title: "AWS",
          description: "Cloud computing platform utilized for infrastructure provisioning, scalable deployments, storage solutions, and application hosting.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["aws"],
          types: ["devops"],
        },
        {
          title: "Figma",
          description: "Collaborative interface design tool used for prototyping, design systems, wireframing, and user experience workflows.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["figma"],
          types: ["design"],
        },
        {
          title: "SQL",
          description: "Standard query language used for managing, manipulating, and retrieving data from relational database systems.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["sql"],
          types: ["database"],
        },
        {
          title: "MySQL",
          description: "Widely adopted relational database management system commonly used in scalable and data-driven web applications.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["mysql"],
          types: ["database"],
        },
        {
          title: "MSSQL",
          description: "Microsoft’s enterprise-grade relational database solution designed for high-performance corporate applications and analytics.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["mssql"],
          types: ["database"],
        },
        {
          title: "PostgreSQL",
          description: "Advanced open-source relational database recognized for reliability, extensibility, and support for complex queries.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["postgresql"],
          types: ["database"],
        },
        {
          title: "Android Studio",
          description: "Official integrated development environment for building, testing, and deploying Android applications.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["android_studio"],
          types: ["mobile"],
        },
        {
          title: "Kotlin",
          description: "Modern programming language for Android development focused on conciseness, interoperability, and type safety.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["kotlin"],
          types: ["mobile"],
        },
        {
          title: "Jetpack Compose",
          description: "Modern declarative UI toolkit for Android development designed to simplify interface creation and state handling.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["jetpack_compose"],
          types: ["mobile"],
        },
        {
          title: "Java",
          description: "Object-oriented programming language extensively used in enterprise systems, backend services, and Android ecosystems.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["java"],
          types: ["backend"],
        },
        {
          title: "C / C++ / C#",
          description: "Collection of programming languages applied to low-level systems, high-performance applications, and enterprise-grade software solutions.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["c_family"],
          types: ["backend"],
        },
        {
          title: "Rust",
          description: "Systems programming language focused on memory safety, concurrency, and high-performance software development.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["rust"],
          types: ["backend"],
        },
        {
          title: "Python",
          description: "Versatile programming language commonly used in automation, backend systems, artificial intelligence, and data analysis.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["python"],
          types: ["backend"],
        },
        {
          title: "Git (GitHub/GitLab)",
          description: "Distributed version control system used for source code management, collaboration workflows, and repository maintenance.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["git_github"],
          types: ["devops"],
        },
        {
          title: "BPMN",
          description: "Graphical notation standard used for modeling, documenting, and optimizing business process workflows.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["bpmn"],
          types: ["backend"],
        },
        {
          title: "UML",
          description: "Modeling language used to visually represent software architecture, system behavior, and object-oriented structures.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["uml"],
          types: ["backend"],
        },
        {
          title: "Storybook",
          description: "Development environment for building, testing, and documenting isolated UI components in scalable frontend applications.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["storybook"],
          types: ["frontend"],
        },
        {
          title: "Data Analysis with Python",
          description: "Utilization of Python libraries for data processing, analysis, visualization, and transformation workflows.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["pandas"],
          types: ["backend"],
        },
        {
          title: "Jest (Testing)",
          description: "JavaScript testing framework used for unit and integration testing to ensure code reliability and maintainability.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["jest"],
          types: ["frontend", "backend"],
        },
        {
          title: "Agile Methodologies (Scrum, Kanban, BDD)",
          description: "Agile project management methodologies focused on iterative delivery, collaboration, adaptability, and continuous improvement.",
          years: "5 years",
          projects: "6",
          img: "",
          badges: ["agile"],
          types: ["management"],
        },
      ] satisfies SkillPageSkill[],
    },
    certificate_page: {
      certificates: [
        {
          id: "c1",
          title: "Bachelor's Degree in Computer Science",
          institution: "UFAM (Federal University of Amazonas)",
          resume:
            "The Rector of the Federal University of Amazonas (UFAM), exercising the authority granted by the institution and considering the completion of the Computer Science program on June 28, 2022, hereby confers upon Emídio José Aranha Cardoso Filho the degree of Bachelor of Computer Science. This diploma grants all legal rights and academic privileges associated with the title. Issued in Manaus on July 14, 2022.",
          img: "c1",
        },
        {
          id: "c2",
          title: "DevTitans Extension Program Certificate",
          institution: "UFAM (Federal University of Amazonas)",
          resume:
            "Certificate awarded to Emídio José Aranha Cardoso Filho for participating in the 6th cohort of the project 'DevTITANS - Training and Development in Android Technologies for Embedded Systems', coordinated by Horácio Antônio Braga Fernandes de Oliveira, held from August 22, 2024 to February 27, 2025, promoted by UFAM’s Extension Office, with a total workload of 240 hours.",
          img: "c2",
        },
        {
          id: "c3",
          title: "JavaScript & TypeScript from Basic to Advanced",
          institution: "Udemy",
          resume:
            "Comprehensive course covering JavaScript and TypeScript from foundational concepts to advanced full stack development practices. Topics include Vanilla JavaScript, Node.js, Express, MongoDB, MySQL, MariaDB, React, Redux, React Hooks, Webpack, Babel, and TypeScript. The program also explores CRUD applications, authentication systems using Sessions and JWT, Linux deployment with NGINX and PM2, SSL/TLS configuration, Git workflows, object-oriented programming, SOLID principles, automated testing with Jest, design patterns, and modern frontend/backend integrations using Next.js and Strapi.",
          img: "c3",
        },
        {
          id: "c4",
          title: "React + Redux, Material UI, Hooks, TypeScript and REST APIs",
          institution: "Udemy",
          resume:
            "Course focused on modern frontend application development using React and technologies from the contemporary JavaScript ecosystem. Covered subjects include JavaScript, TypeScript, HTML, CSS, Bootstrap, Material UI, React class and functional components, Hooks, Redux, REST API integration, and scalable project architecture. The course emphasizes best practices, reusable component design, and practical implementation of modern web applications.",
          img: "c4",
        },
        {
          id: "c5",
          title: "React + Redux Course: Fundamentals and 2 Applications from Scratch",
          institution: "Udemy",
          resume:
            "Hands-on course dedicated to building complete web applications using React and Redux from the ground up. The content covers React fundamentals, Redux state management, Webpack configuration, backend integration with Node.js, Express, and MongoDB, as well as advanced concepts such as dynamic forms and middleware. The program also introduces Next.js, SSR, Firebase, Firestore, TailwindCSS, and TypeScript for the development of scalable and production-ready applications.",
          img: "c5",
        },
        {
          id: "c6",
          title: "Understanding and Documenting REST / RESTful APIs",
          institution: "Udemy",
          resume:
            "Course dedicated to RESTful API architecture, concepts, and documentation practices. The curriculum includes REST maturity models, HTTP communication principles, API versioning, Media Types, caching strategies, authentication using OAuth and JWT, cURL usage for request testing, and API documentation through Swagger. Designed for developers seeking a deeper understanding of modern API development standards and integration practices.",
          img: "c6",
        },
        {
          id: "c7",
          title: "Web Development with PHP and MySQL Database",
          institution: "Udemy",
          resume:
            "Web development course centered on PHP and MySQL for creating dynamic, database-driven applications. The course explores backend development with PHP, SQL fundamentals, relational database management, authentication systems, encrypted password handling, and protection against SQL Injection vulnerabilities. It also covers best practices for integrating web applications with relational databases and building secure server-side solutions.",
          img: "c7",
        },
      ] satisfies CertificateItem[],
    },
    contactme_page: {
      title: "Let's talk? Get in touch with me",
      description:
        "Feel free to reach out to discuss collaboration opportunities, projects, or simply exchange ideas. I’m always open to meaningful connections and continuous learning opportunities.",
      phone_label: "Phone",
      phone: "+55 (92) 98415-8067",
      phone_href: "+5592984158067",
      phone_link: "+55 (92) 98415-8067",
      myEmail_label: "E-mail",
      myEmail: "emidioaranhadeveloper@gmail.com",
      myEmail_link: "emidioaranhadeveloper@gmail.com",
      linkedin_label: "LinkedIn",
      linkedin_url: "https://www.linkedin.com/in/emidio-aranha/",
      linkedin_link: "emidio-aranha",
      github_label: "GitHub",
      github: "https://github.com/EmidioAranha13",
      github_link: "EmidioAranha13",
      location_label: "Location",
      location: "Manaus, AM — Brazil",
      name_label: "Name",
      name_placeholder: "Your name",
      email_label: "E-mail",
      email_placeholder: "your@email.com",
      yourContact: "Your phone",
      yourContact_placeholder: "Your phone number",
      form_phone_invalid_message: "Please enter a valid phone number.",
      subject_label: "Subject",
      subject_placeholder: "Message subject",
      message_label: "Message",
      message_placeholder: "Write your message…",
      form_submit_label: "Send message",
      form_submitting_label: "Sending…",
      form_success_message: "Message sent successfully! I will get back to you soon.",
      form_error_message: "Could not send your message. Please try again shortly.",
      form_modal_success_title: "Sent successfully",
      form_modal_error_title: "Send failed",
      form_modal_processing_title: "Processing",
      form_modal_processing_message: "Processing message",
      form_modal_close_label: "OK",
      form_debug_success_label: "Debug OK",
      form_debug_error_label: "Debug error",
      form_config_missing_message:
        "Form is not configured yet. Set VITE_FORMSPREE_FORM_ID in your .env.local file.",
    },
  },
  ja: {
    name: "エミジオ・アラーニャ",
    role: "フルスタック開発者｜Web・モバイル・IoT",
    about: "プロフィール",
    education: "学習・経歴",
    experience: "経験",
    skills: "スキル",
    certifications: "資格・認定",
    projects: "制作実績",
    contact: "コンタクト",
    downloadCV: "CVをダウンロード",
    contactMe: "気軽に連絡してください",
    techStack: "React／React Native｜Android｜Angular｜PHP｜AI",
    footerRights: "エミジオ・アラーニャ - 2026. All rights reserved.",
    profile_page: {
      second_title: "一般業務",
      professionalResume: [
        "IT業界において5年間の経験を持つフルスタックWeb開発者です。",
        "アマゾナス連邦大学（UFAM）にてコンピュータサイエンスの学士号を取得しました。WebおよびAndroid開発（組み込みシステムを含む）に関するコースを修了し、英語は上級、日本語は中級レベルです。",
        "Webシステム、デスクトップアプリケーション、モバイルアプリの開発に精通しており、リモート情報管理やIoT／組み込みシステム連携など、さまざまな用途に対応可能です。また、要件定義、モックアップ作成、UX/UI設計、アジャイル開発（スクラム、プランニング、デイリー）の進行、メンバーの指導およびユーザートレーニングの経験があります。",
        "常に自己成長を目指し、新しい課題や学習機会に積極的に取り組んでいます。現在は産業向けのコンピュータビジョンおよび機械学習を活用した人工知能の研究に取り組んでいます。",
        <u>主な企業：DELTA SOLUTIONS、ICTS</u>,
        <u>取引先企業：Daikin、INOVA、Conecthus、Elgin、Inventus Power、Flex</u>,
      ],
      globalSkills: [
        "React、React Native、Hooks、Reduxを用いたレスポンシブWebアプリケーションの開発",
        "HTML、CSS、JavaScript、TypeScriptに関する専門知識",
        "REST API、GraphQL、Spring Bootを用いたAPIの設計および統合",
        "Jestを用いた機能検証のためのテストケース作成",
        "クリーンアーキテクチャおよびストーリーテリングの設計への参加",
        "SOLID原則の基礎知識",
        "Git、GitHub、GitLabを用いたバージョン管理、コードレビューおよび分析",
        "LinuxおよびWindows環境でのアプリケーション開発",
        "ログ分析、トラブルシューティング、保守およびソフトウェア改善の経験",
        "Figmaを用いたUX/UI重視のモックアップ作成および調整",
        "デザインシステムの構築および改善",
        "ドキュメントおよび開発記録の管理",
        "タスクの整理、定義および管理",
        "新しいツールへの柔軟な対応力と適応力",
        "CI/CDによるデプロイに関する基礎知識",
      ],
    },
    experience_page: {
      role_title: "役職",
      actions_title: "職務内容",
      projects_title: "関連プロジェクト",
      responsibility_title: "職務内容",
      items: [
        {
          id: "delta",
          label: "デルタソリューションズ",
          role: "フルスタック開発者",
          time_working: "2025年5月 - 現在",
          photos: [
            "photo1",
            "photo2",
            "delta_project_1",
            "delta_project_2",
            "delta_project_3",
            "delta_project_4",
            "delta_project_5",
            "delta_project_6",
            "delta_project_7",
            "delta_project_8",
            "delta_project_9",
            "delta_project_10",
            "delta_project_11",
            "delta_project_12",
          ],
          actions: [
            "React + Vite、React Router、Redux、Node.js、TypeScript、Material UI、Bootstrap、Styled Componentsを使用したWeb/デスクトップアプリの開発",
            "ESP32およびRaspberry Pi（Pi OS）を用いた組み込みシステムの開発",
            "Python + OpenCVによる画像処理ソリューションの実装と産業機器（Keyence）との連携",
            "HMI、MES、AWSを統合したシステムアーキテクチャの設計と実装",
            "Docker、AWS、Pythonを使用したデプロイおよび運用管理",
            "産業環境でのシステム統合、テスト、監視",
            "C#による産業用JIG向けデスクトップアプリの保守と改善",
            "MySQL、SQL Server、PostgreSQLでのデータ設計および操作（CRUD、クエリ、テーブル設計）",
            "技術検証のためのPoC（概念実証）の開発",
            "要件定義および顧客向けカスタマイズ対応",
            "Git（GitHub/GitLab）やTrello、Mondayを使用したアジャイル開発（Scrum/Kanban）",
            "Figmaを用いたUI/UX設計とモックアップ作成",
            "技術ドキュメント作成およびユーザー教育",
            "新メンバーの指導およびオンボーディング支援",
          ],
          projects: [
            {
              project: "FCT（機能回路テスト）カスタムJIGシステム",
              resume: "電子基板テストのための自動化システム",
              tasks_executed: "モックアップからフロントエンド、バックエンド、データベース、Raspberry Piとの通信までシステム全体を開発",
            },
            {
              project: "電子制御・監視パネル",
              resume: "データ収集、監視、制御を行う産業向けシステム",
              tasks_executed: "ダッシュボードの開発（フロント・バックエンド・DB）およびMQTT通信の実装とAWSへのデプロイ",
            },
            {
              project: "電子部品の欠陥検出用画像処理システム",
              resume: "生産ラインで部品検査を行う産業システム",
              tasks_executed: "フロント・バックエンド開発およびModbus通信、画像処理ロジック、Keyence機器との連携",
            },
          ],
        },
        {
          id: "icts",
          label: "ICTS",
          role: "フルスタックWeb/モバイル開発者",
          time_working: "2020年9月 - 2024年2月",
          photos: [],
          actions: [
            "React、Redux、Node.js、PHPなどを用いたWeb/デスクトップアプリ開発",
            "React NativeおよびAndroid Studioによるモバイルアプリ開発",
            "データベース設計および操作（MySQL、SQL Server、PostgreSQL）",
            "GraphQLやSpring Bootなどの技術検証（PoC）",
            "要件定義および顧客対応",
            "Python Pandasによるデータ分析の最適化",
            "レガシーシステムの保守およびリファクタリング",
            "新技術導入のサポートとベストプラクティスの適用",
            "新メンバーの指導および技術オンボーディング",
            "ScrumやKanbanによる開発計画への参加",
            "UI改善およびモックアップの作成",
          ],
          projects: [
            {
              project: "企業管理システム（ダッシュボード付き）",
              resume: "従業員や車両、資材などを管理するシステムの開発",
              tasks_executed: "Web・モバイルフロントエンドおよびAPIの開発",
            },
            {
              project: "LED表示管理システム",
              resume: "LED表示メッセージの管理システム",
              tasks_executed: "機能追加およびフロント・バックエンドの改善",
            },
          ],
        },
        {
          id: "freelance",
          label: "フリーランス",
          role: "フリーランス開発者",
          time_working: "2024年2月 - 2025年4月",
          photos: [],
          actions: [
            "クライアント向けカスタムシステムの開発",
            "レスポンシブUIおよびAPI連携の実装",
            "納品後のサポートと機能改善",
            "Java、PHP（Laravel）、Angularでの開発"
          ],
          projects: [
            {
              project: "Air Quality App",
              resume: "ESP32とセンサーを用いた空気品質監視システム",
              tasks_executed: "Android Studio（Kotlin）での開発、UI設計、Firebase連携、ESP32通信の実装",
            },
            {
              project: "Icomp Numbers",
              resume: "XMLデータ管理システム",
              tasks_executed: "フロント・バックエンド開発およびXMLデータ処理",
            },
            {
              project: "MindTrack Agenda",
              resume: "心理・精神活動管理アプリ（LLM活用）",
              tasks_executed: "Kotlinでの開発およびLLM連携",
            },
            {
              project: "ペットショップ管理システム",
              resume: "ペットショップ業務管理用デスクトップアプリ",
              tasks_executed: "Java SwingとMySQLを使用した開発",
            },
          ],
        },
      ],
    },
    education_page: {
      leafLabels: {
        institution: "教育機関:",
        degree: "学位:",
        period: "期間:",
        location: "都市 | 州:",
        description: "説明:",
        scholar: "奨学金:",
        extra: "その他:",
      },
      education: [
        {
          year: 2012,
          activities: [
            {
              title: "英語コース（初心者向け）",
              institution: "Minds",
              degree: "研修コース",
              period: "2010年1月 - 2012年7月",
              location: "マナウス - AM",
              ended: "7月",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2014,
          activities: [
            {
              title: "英語コース（初級から上級）",
              institution: "SENAC",
              degree: "研修コース",
              period: "2012年8月 - 2014年12月",
              location: "マナウス - AM",
              ended: "12月",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2015,
          activities: [
            {
              title: "学校教育修了",
              institution: "Celus学校",
              degree: "初等・中等教育",
              period: "2000年1月 - 2015年12月",
              location: "マナウス - AM",
              ended: "12月",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2020,
          activities: [
            {
              title: "日本語コース（初級から上級）",
              institution: "NIPPAKU",
              degree: "研修コース",
              period: "2015年1月 - 2020年9月",
              location: "マナウス - AM",
              ended: "9月",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2022,
          activities: [
            {
              title: "コンピュータサイエンス学士",
              institution: "アマゾナス連邦大学（UFAM）",
              degree: "学士号",
              period: "2016年4月 - 2022年7月",
              location: "マナウス - AM",
              ended: "7月",
              description: "",
              scholar: "",
              extra: "",
            },
          ],
        },
        {
          year: 2025,
          activities: [
            {
              title: "DevTitansプログラム",
              institution: "アマゾナス連邦大学（UFAM）",
              degree: "研修プログラム",
              period: "2024年8月 - 2025年2月",
              location: "マナウス - AM",
              ended: "2月",
              description: "組み込みシステム向けAndroid技術の研修と開発",
              scholar: "IFAM教育・研究・普及支援財団（FAEPI）による奨学金",
              extra: "",
            },
          ],
        },
      ],
    },
    skill_page: {
      skills: [
        {
          title: "React",
          description: "コンポーネントベースのライブラリで、Hooksやクラスを使用しながら動的で再利用可能なUIを構築できます。",
          years: "5年",
          projects: "11",
          img: "",
          badges: ["react"],
          types: ["frontend"],
        },
        {
          title: "React Native + Expo",
          description: "JavaScriptとTypeScriptを使用してクロスプラットフォームのモバイルアプリを開発するためのフレームワークです。",
          years: "5年",
          projects: "3",
          img: "",
          badges: ["react_native"],
          types: ["frontend"],
        },
        {
          title: "JavaScript + TypeScript",
          description: "フロントエンドのインタラクティブなUIやバックエンドのビジネスロジック構築に使用される主要な言語です。",
          years: "5年",
          projects: "12",
          img: "",
          badges: ["typescript", "javascript"],
          types: ["frontend", "backend"],
        },
        {
          title: "Redux",
          description: "アプリケーション全体の状態を一元管理するためのライブラリで、ThunkやSaga、RTK Queryの経験があります。",
          years: "5年",
          projects: "6",
          img: "",
          badges: ["redux"],
          types: ["frontend"],
        },
        {
          title: "HTML",
          description: "Webページの構造やコンテンツを定義するための標準マークアップ言語です。",
          years: "5年",
          projects: "6",
          img: "",
          badges: ["html"],
          types: ["frontend"],
        },
        {
          title: "CSS",
          description: "レイアウト、デザイン、レスポンシブ対応などWebインターフェースの見た目を管理するスタイル言語です。",
          years: "5年",
          projects: "6",
          img: "",
          badges: ["css"],
          types: ["frontend"],
        },
        {
          title: "Material UI",
          description: "Google Material Designに基づいたReact用UIコンポーネントライブラリです。",
          years: "5年",
          projects: "3",
          img: "",
          badges: ["material_ui"],
          types: ["frontend"],
        },
        {
          title: "Bootstrap",
          description: "レスポンシブなWebインターフェースを効率的に構築するためのCSSフレームワークです。",
          years: "5年",
          projects: "6",
          img: "",
          badges: ["bootstrap"],
          types: ["frontend"],
        },
        {
          title: "Handlebars",
          description: "バックエンドで動的にHTMLを生成するためのテンプレートエンジンです。",
          years: "1年",
          projects: "1",
          img: "",
          badges: ["handlebars"],
          types: ["frontend", "backend"],
        },
        {
          title: "Style Dictionary",
          description: "複数のプラットフォーム間でデザイントークンを管理・共有するためのツールです。",
          years: "2年",
          projects: "3",
          img: "",
          badges: ["style_dictionary"],
          types: ["frontend"],
        },
        {
          title: "Unstyled Components",
          description: "スタイルを分離し、CSSや他のライブラリで自由にデザインを制御できるコンポーネント設計手法です。",
          years: "5年",
          projects: "6",
          img: "",
          badges: ["styled_components"],
          types: ["frontend"],
        },
        {
          title: "Node.js",
          description: "スケーラブルなバックエンドアプリケーションを構築するためのJavaScript実行環境です。",
          years: "5年",
          projects: "6",
          img: "",
          badges: ["node"],
          types: ["backend"],
        },
        {
          title: "Express",
          description: "Node.js向けの軽量なWebフレームワークで、APIやWebサーバー開発に利用されます。",
          years: "5年",
          projects: "6",
          img: "",
          badges: ["express"],
          types: ["backend"],
        },
        {
          title: "Sequelize",
          description: "Node.jsでリレーショナルデータベース操作を簡単にするORMライブラリです。",
          years: "5年",
          projects: "6",
          img: "",
          badges: ["sequelize"],
          types: ["backend", "database"],
        },
        {
          title: "API REST",
          description: "HTTP通信を利用してシステム間で標準化されたデータ交換を行うAPI設計アーキテクチャです。",
          years: "5年",
          projects: "6",
          img: "",
          badges: ["rest_api"],
          types: ["backend"],
        },
        {
          title: "GraphQL",
          description: "必要なデータのみを効率的に取得できるAPI用クエリ言語です。",
          years: "1年",
          projects: "1",
          img: "",
          badges: ["graphql"],
          types: ["backend"],
        },
        {
          title: "Spring Boot",
          description: "Javaベースのバックエンドアプリケーションを迅速に構築するためのフレームワークです。",
          years: "1年",
          projects: "1",
          img: "",
          badges: ["spring_boot"],
          types: ["backend"],
        },
        {
          title: "Docker",
          description: "アプリケーションをコンテナ化し、異なる環境でも一貫して実行できるプラットフォームです。",
          years: "5年",
          projects: "6",
          img: "",
          badges: ["docker"],
          types: ["devops"],
        },
        {
          title: "AWS",
          description: "クラウドインフラ、ストレージ、デプロイなどを提供するクラウドサービスプラットフォームです。",
          years: "5年",
          projects: "6",
          img: "",
          badges: ["aws"],
          types: ["devops"],
        },
        {
          title: "Figma",
          description: "UIデザイン、プロトタイプ、デザインシステム作成に利用される共同デザインツールです。",
          years: "5年",
          projects: "6",
          img: "",
          badges: ["figma"],
          types: ["design"],
        },
      ] satisfies SkillPageSkill[],
    },
    certificate_page: {
      certificates: [
        {
          id: "c1",
          title: "コンピュータサイエンス学士",
          institution: "UFAM（アマゾナス連邦大学）",
          resume:
            "アマゾナス連邦大学（UFAM）は、2022年6月28日にコンピュータサイエンス課程を修了したEmídio José Aranha Cardoso Filho氏に対し、コンピュータサイエンス学士の学位を授与しました。本 дипломаは法律上の権利および学術的特権を認めるものです。2022年7月14日、マナウスにて発行。",
          img: "c1",
        },
        {
          id: "c2",
          title: "DevTitans エクステンションプログラム修了証",
          institution: "UFAM（アマゾナス連邦大学）",
          resume:
            "Emídio José Aranha Cardoso Filho氏は、「DevTITANS - 組み込みシステム向けAndroid技術トレーニングと開発」第6期プログラムに参加しました。本プログラムはHorácio Antônio Braga Fernandes de Oliveira氏の指導のもと、2024年8月22日から2025年2月27日まで実施され、総学習時間は240時間です。",
          img: "c2",
        },
        {
          id: "c3",
          title: "JavaScript & TypeScript 基礎から上級まで",
          institution: "Udemy",
          resume:
            "JavaScriptとTypeScriptを基礎から上級レベルまで学ぶフルスタック開発コースです。Vanilla JavaScript、Node.js、Express、MongoDB、MySQL、React、Redux、Webpack、Babelなどを学習します。CRUD開発、JWT認証、Linuxデプロイ、Git、SOLID原則、Jestテスト、Next.jsやStrapiを使用したモダン開発も含まれています。",
          img: "c3",
        },
        {
          id: "c4",
          title: "React + Redux, Material UI, Hooks, TypeScript と REST API",
          institution: "Udemy",
          resume:
            "Reactを使用したモダンフロントエンド開発コースです。JavaScript、TypeScript、HTML、CSS、Bootstrap、Material UI、React Hooks、Redux、REST API連携などを学習します。再利用可能なコンポーネント設計や実践的なWebアプリケーション構築に重点を置いています。",
          img: "c4",
        },
        {
          id: "c5",
          title: "React + Redux コース：基礎と2つの実践アプリ開発",
          institution: "Udemy",
          resume:
            "ReactとReduxを使用してゼロからWebアプリケーションを構築する実践コースです。React基礎、Redux状態管理、Webpack設定、Node.js、Express、MongoDBとの連携を学習します。また、Next.js、Firebase、Firestore、TailwindCSS、TypeScriptを使用した最新開発手法も含まれています。",
          img: "c5",
        },
        {
          id: "c6",
          title: "REST / RESTful API の理解とドキュメント作成",
          institution: "Udemy",
          resume:
            "RESTful APIの設計、概念、ドキュメント作成を学ぶコースです。REST成熟度モデル、HTTP通信、APIバージョニング、Media Types、キャッシュ戦略、OAuth・JWT認証、cURLによるテスト、SwaggerによるAPIドキュメント作成を学習します。",
          img: "c6",
        },
        {
          id: "c7",
          title: "PHP と MySQL を使用したWeb開発",
          institution: "Udemy",
          resume:
            "PHPとMySQLを利用した動的Webアプリケーション開発コースです。PHPバックエンド開発、SQL基礎、リレーショナルデータベース管理、ログインシステム、パスワード暗号化、SQL Injection対策などを学習します。安全で効率的なサーバーサイド開発に重点を置いています。",
          img: "c7",
        },
      ] satisfies CertificateItem[],
    },
    contactme_page: {
      title: "お話ししませんか？",
      description:
        "コラボレーションの機会やプロジェクトの相談、またはアイデア交換など、お気軽にご連絡ください。新しいつながりや学びの機会をいつでも歓迎しています。",
      phone_label: "電話番号",
      phone: "+55 (92) 98415-8067",
      phone_href: "+5592984158067",
      phone_link: "+55 (92) 98415-8067",
      myEmail_label: "メール",
      myEmail: "emidioaranhadeveloper@gmail.com",
      myEmail_link: "emidioaranhadeveloper@gmail.com",
      linkedin_label: "LinkedIn",
      linkedin_url: "https://www.linkedin.com/in/emidio-aranha/",
      linkedin_link: "emidio-aranha",
      github_label: "GitHub",
      github: "https://github.com/EmidioAranha13",
      github_link: "EmidioAranha13",
      location_label: "所在地",
      location: "マナウス・AM — ブラジル",
      name_label: "名前",
      name_placeholder: "お名前",
      email_label: "メール",
      email_placeholder: "your@email.com",
      yourContact: "電話番号",
      yourContact_placeholder: "電話番号",
      form_phone_invalid_message: "有効な電話番号を入力してください。",
      subject_label: "件名",
      subject_placeholder: "メッセージの件名",
      message_label: "メッセージ",
      message_placeholder: "メッセージを入力してください…",
      form_submit_label: "メッセージを送信",
      form_submitting_label: "送信中…",
      form_success_message: "送信が完了しました。折り返しご連絡いたします。",
      form_error_message: "送信できませんでした。しばらくしてからもう一度お試しください。",
      form_modal_success_title: "送信完了",
      form_modal_error_title: "送信失敗",
      form_modal_processing_title: "処理中",
      form_modal_processing_message: "メッセージを処理中",
      form_modal_close_label: "OK",
      form_debug_success_label: "Debug OK",
      form_debug_error_label: "Debug エラー",
      form_config_missing_message:
        "フォームが未設定です。.env.local に VITE_FORMSPREE_FORM_ID を設定してください。",
    },
  },
};

export type InfoTextsLanguage = keyof typeof infoTextsCollection;
export type InfoTexts = (typeof infoTextsCollection)[InfoTextsLanguage];